// AUTO-GENERATED by node scripts/update/build-host.mjs — DO NOT EDIT. Source: src/update/host/index.ts

// src/update/gen/updateClient.derived.js
var DEFAULT_CONFIRMATION_TTL_MS = 10 * 6e4;
var DEFAULT_INSTALL_TIMEOUT_MS = 15 * 6e4;
var DEFAULT_PANEL_POLL_MS = 1e3;
var MIN_PANEL_POLL_MS = 250;
function assertPrefix(value, role) {
  if (typeof value !== "string" || value.length === 0) {
    throw new Error("[dsh-plugin-update] " + role + " \u975E\u6CD5\uFF1A\u987B\u4E3A\u975E\u7A7A\u5B57\u7B26\u4E32\uFF08\u6536\u5230 " + JSON.stringify(value) + "\uFF09");
  }
  if (value.includes(".") || value.includes("/") || value.includes("\\") || /\s/.test(value)) {
    throw new Error("[dsh-plugin-update] " + role + " \u975E\u6CD5\uFF1A\u4E0D\u5F97\u542B\u6709\u70B9\u3001\u8DEF\u5F84\u5206\u9694\u7B26\u6216\u7A7A\u767D\uFF08\u6536\u5230 " + JSON.stringify(value) + "\uFF09");
  }
  return value;
}
function buildPhoneNames(prefix) {
  const checked = assertPrefix(prefix, "\u7535\u8BDD\u540D\u524D\u7F00 prefix");
  return {
    updateStatus: checked + ".updateStatus",
    updateCheck: checked + ".updateCheck",
    updateInstall: checked + ".updateInstall"
  };
}
var INSTALL_TIMEOUT_MS = 15 * 6e4;
var CLIENT_POLL = {
  defaultMs: DEFAULT_PANEL_POLL_MS,
  minMs: MIN_PANEL_POLL_MS
};
function buildClientPhoneNames(prefix) {
  return buildPhoneNames(prefix);
}
var UPD_PHONE_NAMES = buildClientPhoneNames("prompt");
var UPD_POLL_MS = CLIENT_POLL.defaultMs;
var UPD_POLL_MIN_MS = CLIENT_POLL.minMs;
var UPD_STATUS = UPD_PHONE_NAMES.updateStatus;
var UPD_CHECK = UPD_PHONE_NAMES.updateCheck;
var UPD_INSTALL = UPD_PHONE_NAMES.updateInstall;

// src/update/bridge.ts
var UPDATE_STATUS_PATH = "/_dsh/dsh-prompt/update/status";
var UPDATE_CHECK_PATH = "/_dsh/dsh-prompt/update/check";
var UPDATE_INSTALL_PATH = "/_dsh/dsh-prompt/update/install";

// src/update/host/index.ts
var PLUGIN_ID = "dsh-prompt";
var PHONE_PREFIX = "prompt";
var TARGET_PACKAGE_NAME = "dsh-prompt";
var UNAVAILABLE = "update-capability-unavailable";
var UPDATE_ROUTE_FAMILY = UPDATE_STATUS_PATH.slice(0, UPDATE_STATUS_PATH.lastIndexOf("/"));
var SNAPSHOT_FIELDS = [
  "runningVersion",
  // 正在跑的版本
  "installedVersion",
  // 磁盘上装着的版本（与上一条不同即待重启）
  "latestVersion",
  // 官方源上的最新版本（没查过就是 null）
  "canInstall",
  // 现在能不能装
  "blockedReason",
  // 装不了的原因（八种之一，能装时为 null）
  "job"
  // 进行中/上次的安装任务
];
function createBridgeLog(logReady) {
  let cap = null;
  let unknownReported = false;
  const failedStates = /* @__PURE__ */ new Set();
  if (logReady && typeof logReady.then === "function") {
    logReady.then(
      (ready) => {
        cap = ready && typeof ready.log === "function" ? ready : null;
      },
      () => {
        cap = null;
      }
    );
  }
  function noteFail(method, kind) {
    const key = failKeyOf(method, kind);
    if (failedStates.has(key)) return false;
    failedStates.add(key);
    return true;
  }
  function clearFails(method) {
    const prefix = failKeyOf(method, "");
    for (const key of failedStates) if (key.startsWith(prefix)) failedStates.delete(key);
  }
  return {
    fire(level, event, fields) {
      try {
        if (!cap) return;
        const f = fields ?? {};
        switch (String(event ?? "")) {
          case "host.call": {
            const safe = safeFields(f);
            if (safe.ok === true) clearFails(String(safe.method ?? ""));
            cap.log("host.call", { ...safe });
            return;
          }
          case "host.call.fail": {
            const safe = safeFields(f);
            if (!noteFail(String(safe.method ?? ""), String(safe.kind ?? ""))) return;
            cap.log("host.call.fail", { ...safe });
            return;
          }
          case "update.install.exec": {
            const safe = safeFields(f);
            cap.log("update.install.exec", { ...safe });
            return;
          }
          default:
            if (unknownReported) return;
            unknownReported = true;
            cap.log("update.route.fail", {
              route: UPDATE_ROUTE_FAMILY,
              reason: "unknown-event",
              errorHash: hash8(String(event ?? ""))
            });
        }
      } catch (e) {
      }
    }
  };
}
var SAFE_VALUE_RE = /^[A-Za-z0-9._:\/-]{0,64}$/;
function toText(value) {
  try {
    const json = JSON.stringify(value);
    return typeof json === "string" ? json : String(value);
  } catch (e) {
    return String(value);
  }
}
function safeValue(value) {
  if (value === void 0 || value === null) return value;
  if (typeof value === "number" || typeof value === "boolean") return value;
  const text = typeof value === "string" ? value : toText(value);
  return SAFE_VALUE_RE.test(text) ? text : hash8(text);
}
function safeFields(fields) {
  const out = { ...fields };
  for (const key of Object.keys(out)) out[key] = safeValue(out[key]);
  return out;
}
function failKeyOf(method, kind) {
  return method + "\0" + kind;
}
function hash8(value) {
  const text = String(value ?? "");
  let h = 5381;
  for (let i = 0; i < text.length; i++) h = (h << 5) + h + text.charCodeAt(i) >>> 0;
  return ("0000000" + h.toString(16)).slice(-8);
}
async function createUpdateCapability(options = {}) {
  let mod = options.hostUpdate ?? await import("dsh-plugin-update").catch((e) => e);
  if (mod instanceof Error) {
    return degradedCapability(`dep-load-fail: ${mod.message}`, options.onFallback);
  }
  let update;
  const bridgeLog = createBridgeLog(options.logReady);
  try {
    update = mod.createHostUpdate(
      { ctx: options.ctx ?? null, logCtx: bridgeLog },
      {
        pluginId: PLUGIN_ID,
        prefix: PHONE_PREFIX,
        targetPackageName: TARGET_PACKAGE_NAME
        // 其余全走包默认值（官方源、家目录、超时、凭证有效期、轮询间隔），本票一个都不动。
      }
    );
  } catch (e) {
    return degradedCapability(String(e?.message || e), options.onFallback);
  }
  const phoneNames = update.phoneNames;
  const phones = {
    status: phoneNames.updateStatus,
    check: phoneNames.updateCheck,
    install: phoneNames.updateInstall
  };
  const routes = {
    [UPDATE_STATUS_PATH]: phones.status,
    [UPDATE_CHECK_PATH]: phones.check,
    [UPDATE_INSTALL_PATH]: phones.install
  };
  function logPhoneFail(method, kind, message) {
    bridgeLog.fire("warn", "host.call.fail", {
      method,
      kind,
      errorHash: hash8(message),
      pluginId: PLUGIN_ID
    });
  }
  return {
    ok: true,
    phoneNames: { ...phoneNames },
    paths: { status: UPDATE_STATUS_PATH, check: UPDATE_CHECK_PATH, install: UPDATE_INSTALL_PATH },
    /** 快照六字段名（只读常量，给回归脚本与将来的面板对账用）。 */
    snapshotFields: SNAPSHOT_FIELDS,
    /**
     * 电话调用口：路由按 URL 找人，这里按电话名找函数。回包形状 = 更新包 loggedPhone 的形状
     * （`{ ok, snapshot, manual, receipt }`）。
     */
    async runRoute(path, args) {
      const phone = routes[path];
      if (phone === void 0) {
        logPhoneFail(path, "unknown-phone", `no update phone for ${path}`);
        return failed("unknown-phone", `no update phone for ${path}`);
      }
      try {
        return await update.handlers[phone](args ?? {});
      } catch (e) {
        const message = String(e?.message || e);
        logPhoneFail(String(phone), "phone-failed", message);
        return failed("phone-failed", message);
      }
    }
  };
}
function failed(error, errorKind) {
  return { ok: false, error, errorKind };
}
function degradedCapability(reason, onFallback) {
  try {
    if (typeof onFallback === "function") onFallback(reason);
  } catch (e) {
  }
  return {
    ok: false,
    reason,
    phoneNames: {},
    paths: { status: UPDATE_STATUS_PATH, check: UPDATE_CHECK_PATH, install: UPDATE_INSTALL_PATH },
    snapshotFields: SNAPSHOT_FIELDS,
    async runRoute() {
      return failed(UNAVAILABLE, reason);
    }
  };
}
export {
  PHONE_PREFIX,
  PLUGIN_ID,
  SNAPSHOT_FIELDS,
  TARGET_PACKAGE_NAME,
  createUpdateCapability
};
