// AUTO-GENERATED by node scripts/update/build-host.mjs — DO NOT EDIT. Source: src/update/host/index.ts
// 本产物内联的 dsh-plugin-update 版本标记（#58）：test:issue-39 会断言这一行 ==
// package.json 的 devDependencies["dsh-plugin-update"] —— 升了包版本却忘了重建，这里就对不上。
const INLINED_UPDATE_PKG_VERSION = '0.1.1';

var __defProp = Object.defineProperty;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __esm = (fn, res, err) => function __init() {
  if (err) throw err[0];
  try {
    return fn && (res = (0, fn[__getOwnPropNames(fn)[0]])(fn = 0)), res;
  } catch (e) {
    throw err = [e], e;
  }
};
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};

// node_modules/dsh-plugin-update/dist/config.js
function assertPluginId(value) {
  if (typeof value !== "string" || value.length === 0) {
    throw new Error("[dsh-plugin-update] \u63D2\u4EF6\u6807\u8BC6 pluginId \u5FC5\u586B\uFF1A\u987B\u4E3A\u975E\u7A7A\u5B57\u7B26\u4E32\uFF08\u6536\u5230 " + JSON.stringify(value) + "\uFF09");
  }
  if (value.includes("/") || value.includes("\\") || value.includes("\0")) {
    throw new Error("[dsh-plugin-update] \u63D2\u4EF6\u6807\u8BC6 pluginId \u975E\u6CD5\uFF1A\u4E0D\u5F97\u542B\u6709\u8DEF\u5F84\u5206\u9694\u7B26\uFF08\u6536\u5230 " + JSON.stringify(value) + "\uFF09");
  }
  return value;
}
function assertPrefix2(value, role) {
  if (typeof value !== "string" || value.length === 0) {
    throw new Error("[dsh-plugin-update] " + role + " \u975E\u6CD5\uFF1A\u987B\u4E3A\u975E\u7A7A\u5B57\u7B26\u4E32\uFF08\u6536\u5230 " + JSON.stringify(value) + "\uFF09");
  }
  if (value.includes(".") || value.includes("/") || value.includes("\\") || /\s/.test(value)) {
    throw new Error("[dsh-plugin-update] " + role + " \u975E\u6CD5\uFF1A\u4E0D\u5F97\u542B\u6709\u70B9\u3001\u8DEF\u5F84\u5206\u9694\u7B26\u6216\u7A7A\u767D\uFF08\u6536\u5230 " + JSON.stringify(value) + "\uFF09");
  }
  return value;
}
function assertPositiveFinite(value, role) {
  if (typeof value !== "number" || !Number.isFinite(value) || value <= 0) {
    throw new Error("[dsh-plugin-update] " + role + " \u975E\u6CD5\uFF1A\u987B\u4E3A\u6709\u9650\u5927\u4E8E 0 \u7684\u6570\uFF08\u6536\u5230 " + JSON.stringify(value) + "\uFF09");
  }
  return value;
}
function resolveUpdateConfig(input) {
  if (!input || typeof input !== "object") {
    throw new Error("[dsh-plugin-update] \u5EFA\u66F4\u65B0\u80FD\u529B\u7F3A\u5C11\u914D\u7F6E\uFF1A\u63D2\u4EF6\u6807\u8BC6 pluginId \u5FC5\u586B");
  }
  const pluginId = assertPluginId(input.pluginId);
  const prefix = input.prefix === void 0 ? DEFAULT_PREFIX : assertPrefix2(input.prefix, "\u7535\u8BDD\u540D\u524D\u7F00 prefix");
  const targetPackageName = input.targetPackageName === void 0 ? DEFAULT_TARGET_PACKAGE : String(input.targetPackageName);
  if (!targetPackageName) {
    throw new Error("[dsh-plugin-update] \u76EE\u6807\u5305\u540D targetPackageName \u975E\u6CD5\uFF1A\u987B\u4E3A\u975E\u7A7A\u5B57\u7B26\u4E32");
  }
  const registryUrl = input.registryUrl === void 0 ? DEFAULT_REGISTRY : String(input.registryUrl);
  if (!registryUrl) {
    throw new Error("[dsh-plugin-update] \u5B98\u65B9\u6E90 registryUrl \u975E\u6CD5\uFF1A\u987B\u4E3A\u975E\u7A7A\u5B57\u7B26\u4E32");
  }
  const homeDir = input.homeDir === void 0 ? null : String(input.homeDir);
  const checkTimeoutMs = input.checkTimeoutMs === void 0 ? DEFAULT_CHECK_TIMEOUT_MS : assertPositiveFinite(input.checkTimeoutMs, "\u8054\u7F51\u8D85\u65F6 checkTimeoutMs");
  const confirmationTtlMs = input.confirmationTtlMs === void 0 ? DEFAULT_CONFIRMATION_TTL_MS2 : assertPositiveFinite(input.confirmationTtlMs, "\u51ED\u8BC1\u6709\u6548\u671F confirmationTtlMs");
  const installTimeoutMs = input.installTimeoutMs === void 0 ? DEFAULT_INSTALL_TIMEOUT_MS2 : assertPositiveFinite(input.installTimeoutMs, "\u5B89\u88C5\u65F6\u9650 installTimeoutMs");
  const panelPollMs = input.panelPollMs === void 0 ? DEFAULT_PANEL_POLL_MS2 : assertPositiveFinite(input.panelPollMs, "\u9762\u677F\u8F6E\u8BE2 panelPollMs");
  if (panelPollMs < MIN_PANEL_POLL_MS2) {
    throw new Error("[dsh-plugin-update] \u9762\u677F\u8F6E\u8BE2 panelPollMs \u975E\u6CD5\uFF1A\u4E0D\u5F97\u5C0F\u4E8E 250 \u6BEB\u79D2\uFF08\u6536\u5230 " + JSON.stringify(input.panelPollMs) + "\uFF09");
  }
  return { pluginId, prefix, targetPackageName, registryUrl, homeDir, checkTimeoutMs, confirmationTtlMs, installTimeoutMs, panelPollMs };
}
function buildPhoneNames2(prefix) {
  const checked = assertPrefix2(prefix, "\u7535\u8BDD\u540D\u524D\u7F00 prefix");
  return {
    updateStatus: checked + ".updateStatus",
    updateCheck: checked + ".updateCheck",
    updateInstall: checked + ".updateInstall"
  };
}
function buildPhoneName(prefix, action) {
  return buildPhoneNames2(prefix)[action];
}
var DEFAULT_PREFIX, DEFAULT_TARGET_PACKAGE, DEFAULT_REGISTRY, LEGACY_PLUGIN_ID, STATE_FILE, LOCK_FILE, BACKUP_FILE, DEFAULT_CHECK_TIMEOUT_MS, DEFAULT_CONFIRMATION_TTL_MS2, DEFAULT_INSTALL_TIMEOUT_MS2, DEFAULT_PANEL_POLL_MS2, MIN_PANEL_POLL_MS2;
var init_config = __esm({
  "node_modules/dsh-plugin-update/dist/config.js"() {
    DEFAULT_PREFIX = "wf";
    DEFAULT_TARGET_PACKAGE = "dsh-mattpocock-skills-deck";
    DEFAULT_REGISTRY = "https://registry.npmjs.org/";
    LEGACY_PLUGIN_ID = "dsh-mattpocock-skills-deck";
    STATE_FILE = "state.json";
    LOCK_FILE = "install.lock";
    BACKUP_FILE = "before.json";
    DEFAULT_CHECK_TIMEOUT_MS = 1e4;
    DEFAULT_CONFIRMATION_TTL_MS2 = 10 * 6e4;
    DEFAULT_INSTALL_TIMEOUT_MS2 = 15 * 6e4;
    DEFAULT_PANEL_POLL_MS2 = 1e3;
    MIN_PANEL_POLL_MS2 = 250;
  }
});

// node_modules/dsh-plugin-update/dist/commands.js
function validVersion(v) {
  return typeof v === "string" && /^\d+\.\d+\.\d+$/.test(v);
}
function parseTriple(v) {
  const parts = String(v).split(".");
  if (parts.length > 3) return null;
  const nums = [];
  for (const p of parts) {
    if (!/^\d+$/.test(p)) return null;
    const n = Number(p);
    if (!Number.isSafeInteger(n)) return null;
    nums.push(n);
  }
  while (nums.length < 3) nums.push(0);
  return [nums[0], nums[1], nums[2]];
}
function compareVersions(a, b) {
  const pa = parseTriple(a);
  const pb = parseTriple(b);
  if (!pa || !pb) throw new Error("invalid-release");
  for (let i = 0; i < 3; i++) {
    if (pa[i] < pb[i]) return -1;
    if (pa[i] > pb[i]) return 1;
  }
  return 0;
}
function usableProfileName(raw) {
  const name = typeof raw === "string" ? raw.trim() : "";
  if (!name || name.length > 255 || name.startsWith("-")) return null;
  if ([".", "..", "node_modules"].includes(name)) return null;
  return name;
}
function installRecipe(input) {
  const name = usableProfileName(input?.profileName);
  const version = input?.version;
  if (!name || !validVersion(version)) return null;
  const kind = input?.environmentKind;
  if (kind !== "desktop" && kind !== "cli") return null;
  const targetName = input?.targetPackageName ?? PACKAGE_NAME;
  const registry = input?.registryUrl ?? NPM_REGISTRY;
  const timeoutMs = input?.timeoutMs ?? INSTALL_TIMEOUT_MS2;
  if (!targetName || !registry) return null;
  return {
    route: kind === "desktop" ? "desktop-service" : "cli-process",
    profileName: name,
    version,
    // 参数数组原样交给命令行工具：使用范围名不做引号包裹、不按空格拆分。
    pluginArgs: ["add", "--save-exact", `${targetName}@${version}`, `--registry=${registry}`],
    timeoutMs
  };
}
function manualCommand(input) {
  if (input.sourceInstall || input.blockedReason === "source-install" || input.blockedReason === "unknown-profile") return null;
  const name = usableProfileName(input.profileName);
  if (!name) return null;
  const targetName = input.targetPackageName ?? PACKAGE_NAME;
  const registry = input.registryUrl ?? NPM_REGISTRY;
  if (!targetName || !registry) return null;
  const arg = /^[A-Za-z0-9_.-]+$/.test(name) ? name : JSON.stringify(name);
  const picks = [input.latestVersion, input.jobTargetVersion, input.installedVersion].filter(validVersion);
  let version = picks.length > 0 ? picks[0] : "latest";
  try {
    const ranked = picks.filter((v) => compareVersions(v, input.runningVersion) >= 0);
    if (ranked.length > 0) {
      version = ranked[0];
      for (const v of ranked) if (compareVersions(v, version) === 1) version = v;
    }
  } catch {
  }
  return `dsh plugin --profile ${arg} add --save-exact ${targetName}@${version} --registry=${registry}`;
}
var PACKAGE_NAME, NPM_REGISTRY, INSTALL_TIMEOUT_MS2;
var init_commands = __esm({
  "node_modules/dsh-plugin-update/dist/commands.js"() {
    PACKAGE_NAME = "dsh-mattpocock-skills-deck";
    NPM_REGISTRY = "https://registry.npmjs.org/";
    INSTALL_TIMEOUT_MS2 = 15 * 6e4;
  }
});

// node_modules/dsh-plugin-update/dist/service.js
function validRequestId(v) {
  return typeof v === "string" && v.trim().length >= 1 && v.trim().length <= 128;
}
function updateError(code) {
  return Object.assign(new Error(code), { code });
}
function validVersion2(v) {
  return typeof v === "string" && /^\d+\.\d+\.\d+$/.test(v);
}
function parseTriple2(v) {
  const parts = String(v).split(".");
  if (parts.length > 3) return null;
  const nums = [];
  for (const p of parts) {
    if (!/^\d+$/.test(p)) return null;
    const n = Number(p);
    if (!Number.isSafeInteger(n)) return null;
    nums.push(n);
  }
  while (nums.length < 3) nums.push(0);
  return [nums[0], nums[1], nums[2]];
}
function compareVersions2(a, b) {
  const pa = parseTriple2(a);
  const pb = parseTriple2(b);
  if (!pa || !pb) throw updateError("invalid-release");
  for (let i = 0; i < 3; i++) {
    if (pa[i] < pb[i]) return -1;
    if (pa[i] > pb[i]) return 1;
  }
  return 0;
}
function compareOne(node, op, target) {
  const order = compareTriple(node, target);
  if (op === "=" || op === "") return order === 0;
  if (op === ">") return order === 1;
  if (op === ">=") return order >= 0;
  if (op === "<") return order === -1;
  if (op === "<=") return order <= 0;
  return true;
}
function compareTriple(a, b) {
  for (let i = 0; i < 3; i++) {
    if (a[i] < b[i]) return -1;
    if (a[i] > b[i]) return 1;
  }
  return 0;
}
function upperBound(t, kind, kept) {
  if (kind === "^") {
    if (kept >= 1) return [t[0] + 1, 0, 0];
    return [0, t[1] + 1, 0];
  }
  if (kept >= 2) return [t[0], t[1] + 1, 0];
  return [t[0] + 1, 0, 0];
}
function satisfiesNodeRange(nodeVersion, range) {
  if (range === void 0 || range === null) return true;
  const text = String(range).trim();
  if (text === "" || text === "*") return true;
  const node = parseTriple2(String(nodeVersion).replace(/^v/, ""));
  if (!node) return true;
  if (text.includes("||")) return true;
  const parts = text.split(/\s+/).filter(Boolean);
  if (parts.length === 0) return true;
  for (const part2 of parts) {
    const m = part2.match(/^(\^|~|>=|<=|>|<|=)?(.+)$/);
    if (!m) return true;
    const op = m[1] || "";
    const target = parseTriple2(m[2]);
    if (!target) return true;
    if (op === "^" || op === "~") {
      const kept = m[2].split(".").length;
      if (compareTriple(node, target) < 0) return false;
      if (compareTriple(node, upperBound(target, op, kept)) >= 0) return false;
      continue;
    }
    if (!compareOne(node, op, target)) return false;
  }
  return true;
}
function byteLength(text) {
  try {
    return new TextEncoder().encode(text).length;
  } catch {
    return text.length;
  }
}
function timeoutSignal(ms) {
  try {
    const ctor = globalThis.AbortSignal;
    if (ctor && typeof ctor.timeout === "function") return ctor.timeout(ms);
  } catch {
  }
  return void 0;
}
async function fetchNpmRelease(fetchImpl, timeoutMs = CHECK_TIMEOUT_MS, opts) {
  const targetName = opts?.targetPackageName ?? PACKAGE_NAME2;
  const registry = opts?.registryUrl ?? NPM_REGISTRY2;
  let response = null;
  try {
    response = await fetchImpl(`${registry}${encodeURIComponent(targetName)}/latest`, {
      headers: { accept: "application/json" },
      redirect: "error",
      signal: timeoutSignal(timeoutMs)
    });
  } catch {
    throw updateError("check-failed");
  }
  try {
    if (!response.ok) throw updateError("check-failed");
    const declared = Number(response.headers.get("content-length"));
    if (Number.isFinite(declared) && declared > MAX_METADATA_BYTES) throw updateError("invalid-release");
    const text = await response.text();
    if (byteLength(text) > MAX_METADATA_BYTES) throw updateError("invalid-release");
    const value = JSON.parse(text);
    if (value.name !== targetName || !validVersion2(value.version)) throw updateError("invalid-release");
    const version = value.version;
    const nodeRange = value.engines?.node;
    if (nodeRange !== void 0 && typeof nodeRange !== "string") throw updateError("invalid-release");
    const tarballText = value.dist?.tarball;
    const integrity = value.dist?.integrity;
    let tarball;
    try {
      tarball = new URL(String(tarballText));
    } catch {
      throw updateError("invalid-release");
    }
    const registryOrigin = new URL(registry).origin;
    const shapeOk = tarball.origin === registryOrigin && !tarball.username && !tarball.password && !tarball.search && !tarball.hash && tarball.pathname === `/${targetName}/-/${targetName}-${version}.tgz` && typeof integrity === "string" && new RegExp(INTEGRITY_PATTERN).test(integrity);
    if (!shapeOk) throw updateError("invalid-release");
    return { version, nodeRange: typeof nodeRange === "string" ? nodeRange : "*", integrity, tarball: tarball.href };
  } catch (error) {
    if (error?.code === "check-failed") throw error;
    if (error?.code === "invalid-release") throw error;
    if (response !== null && response.ok) throw updateError("invalid-release");
    throw updateError("check-failed");
  }
}
function createUpdateCore(ports) {
  const checkTimeoutMs = ports.checkTimeoutMs ?? CHECK_TIMEOUT_MS;
  const confirmationTtlMs = ports.confirmationTtlMs ?? CONFIRMATION_TTL_MS;
  const targetPackageName = ports.targetPackageName ?? PACKAGE_NAME2;
  const registryUrl = ports.registryUrl ?? NPM_REGISTRY2;
  function fetchRelease() {
    return fetchNpmRelease(ports.fetchImpl, checkTimeoutMs, { targetPackageName, registryUrl });
  }
  let checked = null;
  let checking = null;
  let lastCheckAt = -Infinity;
  let activeJobId = null;
  let memJob = null;
  let memLock = null;
  async function loadJob() {
    try {
      return ports.readJob ? await ports.readJob() ?? null : memJob;
    } catch {
      throw updateError("install-failed");
    }
  }
  async function saveJob(job) {
    try {
      if (ports.writeJob) await ports.writeJob(job);
      else memJob = job;
    } catch {
      throw updateError("install-failed");
    }
  }
  async function acquire(lockId) {
    try {
      if (ports.tryAcquireLock) return await ports.tryAcquireLock(lockId);
    } catch {
      return false;
    }
    if (memLock !== null) return false;
    memLock = lockId;
    return true;
  }
  async function release(lockId) {
    try {
      if (ports.releaseLock) await ports.releaseLock(lockId);
      else if (memLock === lockId) memLock = null;
    } catch {
    }
  }
  function healJob(job, env) {
    if (!job) return null;
    if (job.state === "installing" || job.state === "verifying") {
      return job.id === activeJobId ? job : { ...job, state: "interrupted", message: "recovery-required", requestId: job.requestId ?? null };
    }
    if (job.state === "restart-required" || job.state === "completed") {
      if (!job.targetVersion || env.installedVersion !== job.targetVersion) {
        return { ...job, state: "interrupted", message: "installation-changed", requestId: job.requestId ?? null };
      }
      const runningVersion = ports.readRunningVersion();
      return { ...job, state: runningVersion === job.targetVersion ? "completed" : "restart-required", requestId: job.requestId ?? null };
    }
    return job;
  }
  function buildSnapshot(env, job) {
    let blockedReason = env.blockedReason ?? checked?.blockedReason ?? null;
    if (job?.state === "interrupted" || job?.state === "failed") {
      if (env.installedVersion !== ports.readRunningVersion()) blockedReason = "recovery-required";
    } else if (job?.state === "restart-required" || env.installedVersion && env.installedVersion !== ports.readRunningVersion()) {
      blockedReason = "pending-restart";
    }
    const busy = job?.state === "installing" || job?.state === "verifying";
    const fresh = checked !== null && checked.checkId !== null && ports.now() < checked.expiresAt;
    const runningVersion = ports.readRunningVersion();
    const canInstall = Boolean(
      env.eligible && !blockedReason && !busy && fresh && checked?.installationKey === env.installationKey && validVersion2(runningVersion) && checked?.release && compareVersions2(checked.release.version, runningVersion) === 1
    );
    return {
      runningVersion,
      installedVersion: env.installedVersion ?? null,
      latestVersion: checked?.release.version ?? null,
      canInstall,
      blockedReason,
      job
    };
  }
  async function status() {
    const env = await ports.readInstalled();
    const job = healJob(await loadJob(), env);
    return buildSnapshot(env, job);
  }
  async function check() {
    if (checking) return checking;
    if (checked?.checkId && ports.now() - lastCheckAt < RECHECK_WINDOW_MS) {
      const env = await ports.readInstalled();
      const snapshot = buildSnapshot(env, healJob(await loadJob(), env));
      return { snapshot, receipt: snapshot.canInstall ? toReceipt() : null };
    }
    lastCheckAt = ports.now();
    checking = (async () => {
      try {
        const env = await ports.readInstalled();
        const release2 = await fetchRelease();
        checked = {
          release: release2,
          checkId: ports.randomId(),
          checkedAt: ports.now(),
          expiresAt: ports.now() + confirmationTtlMs,
          installationKey: env.installationKey,
          blockedReason: satisfiesNodeRange(ports.nodeVersion, release2.nodeRange) ? null : "incompatible-node"
        };
        const snapshot = buildSnapshot(env, healJob(await loadJob(), env));
        return { snapshot, receipt: snapshot.canInstall ? toReceipt() : null };
      } catch (error) {
        if (checked) checked = { ...checked, checkId: null, expiresAt: 0 };
        throw error;
      } finally {
        checking = null;
      }
    })();
    return checking;
  }
  function toReceipt() {
    if (!checked?.checkId) return null;
    return { checkId: checked.checkId, checkedAt: checked.checkedAt, expiresAt: checked.expiresAt };
  }
  async function runBackground(job, envAtStart) {
    try {
      if (ports.runInstall) await ports.runInstall({ version: job.targetVersion, profileName: envAtStart.profileName, environmentKind: envAtStart.environmentKind });
      else throw updateError("unsupported");
      const doing = { ...job, state: "verifying", message: null };
      activeJobId = doing.id;
      await saveJob(doing);
      const env = await ports.readInstalled();
      if (env.installedVersion !== job.targetVersion) throw updateError("install-failed");
      if (env.blockedReason && env.blockedReason !== "pending-restart") throw updateError("install-failed");
      const done = { ...doing, state: "restart-required", message: null };
      await saveJob(done);
    } catch (error) {
      const code = error?.code;
      const message = code === "installation-changed" || code === "registry-conflict" || code === "install-failed" ? String(code) : "install-failed";
      const failedJob = { ...job, state: "failed", message, requestId: job.requestId ?? null };
      try {
        await saveJob(failedJob);
      } catch {
        memJob = failedJob;
      }
    } finally {
      await release(job.id);
      if (activeJobId === job.id) activeJobId = null;
    }
  }
  async function install(args) {
    const checkId = typeof args?.checkId === "string" ? args.checkId : "";
    const requestId = typeof args?.requestId === "string" ? args.requestId : "";
    if (!checkId || !validRequestId(requestId)) throw updateError("check-expired");
    let env = await ports.readInstalled();
    let previous = healJob(await loadJob(), env);
    if (previous?.requestId === requestId) return buildSnapshot(env, previous);
    if (previous?.state === "installing" || previous?.state === "verifying" || previous?.state === "restart-required") {
      throw updateError("update-busy");
    }
    if (!checked || !checked.checkId || checked.checkId !== checkId || ports.now() >= checked.expiresAt) {
      throw updateError("check-expired");
    }
    if (env.installationKey !== checked.installationKey) throw updateError("installation-changed");
    if (!buildSnapshot(env, previous).canInstall) {
      throw updateError(env.blockedReason ?? checked.blockedReason ?? "update-busy");
    }
    const job = {
      id: ports.randomId(),
      state: "installing",
      targetVersion: checked.release.version,
      message: null,
      requestId
    };
    if (!await acquire(job.id)) throw updateError("update-busy");
    try {
      const current = await fetchRelease();
      if (JSON.stringify(current) !== JSON.stringify(checked.release)) throw updateError("check-expired");
      env = await ports.readInstalled();
      if (env.installationKey !== checked.installationKey) throw updateError("installation-changed");
      if (!env.eligible || env.blockedReason) throw updateError(env.blockedReason ?? "update-busy");
      if (ports.backupJob) await ports.backupJob(job);
      await saveJob(job);
      activeJobId = job.id;
    } catch (error) {
      await release(job.id);
      throw error;
    }
    void runBackground(job, env).catch(() => {
    });
    return buildSnapshot(env, job);
  }
  return { status, check, install };
}
var PACKAGE_NAME2, NPM_REGISTRY2, CHECK_TIMEOUT_MS, CONFIRMATION_TTL_MS, RECHECK_WINDOW_MS, MAX_METADATA_BYTES, INTEGRITY_PATTERN;
var init_service = __esm({
  "node_modules/dsh-plugin-update/dist/service.js"() {
    PACKAGE_NAME2 = "dsh-mattpocock-skills-deck";
    NPM_REGISTRY2 = "https://registry.npmjs.org/";
    CHECK_TIMEOUT_MS = 1e4;
    CONFIRMATION_TTL_MS = 10 * 6e4;
    RECHECK_WINDOW_MS = 2e3;
    MAX_METADATA_BYTES = 256 * 1024;
    INTEGRITY_PATTERN = "^sha512-[A-Za-z0-9+/]{86}==$";
  }
});

// node_modules/dsh-plugin-update/dist/store.js
import { createHash, randomUUID } from "node:crypto";
import { mkdir, open, readFile, rename, realpath, stat, unlink, writeFile } from "node:fs/promises";
import { dirname, isAbsolute, join, resolve } from "node:path";
function fail(code) {
  return Object.assign(new Error(code), { code });
}
function shortHash(text) {
  try {
    return createHash("sha256").update(String(text)).digest("hex").slice(0, 24);
  } catch {
    return "00000000";
  }
}
function pathsForUpdate(homeDir, pluginId, profileDir) {
  if (typeof homeDir !== "string" || !homeDir || typeof profileDir !== "string" || !profileDir) return null;
  if (typeof pluginId !== "string" || !pluginId) return null;
  const directory = join(homeDir, LEGACY_SEGMENT, pluginId, shortHash(profileDir));
  return { directory, state: join(directory, STATE_FILE), lock: join(directory, LOCK_FILE), backup: join(directory, BACKUP_FILE) };
}
function legacyPathsForUpdate(homeDir, profileDir) {
  if (typeof homeDir !== "string" || !homeDir || typeof profileDir !== "string" || !profileDir) return null;
  const directory = join(homeDir, LEGACY_SEGMENT, LEGACY_DIR_PLUGIN, shortHash(profileDir));
  return { directory, state: join(directory, STATE_FILE), lock: join(directory, LOCK_FILE), backup: join(directory, BACKUP_FILE) };
}
async function readJsonGuarded(filename, missing) {
  try {
    if ((await stat(filename)).size > 10 * 1024 * 1024) throw fail("install-failed");
    return JSON.parse(await readFile(filename, "utf8"));
  } catch (error) {
    if (error && error.code === "ENOENT") return missing;
    throw error && error.code ? error : fail("install-failed");
  }
}
async function writeJsonAtomic(filename, value) {
  const temporary = `${filename}.${randomUUID()}.tmp`;
  try {
    await writeFile(temporary, `${JSON.stringify(value, null, 2)}
`, { mode: 384, flag: "wx" });
    await rename(temporary, filename);
  } catch {
    throw fail("install-failed");
  } finally {
    await unlink(temporary).catch(() => {
    });
  }
}
function createUpdateDiskPorts(homeDir, pluginId, profileDir, deps = {}) {
  const paths = pathsForUpdate(homeDir, pluginId, profileDir);
  const legacyPaths = pluginId === LEGACY_DIR_PLUGIN ? null : legacyPathsForUpdate(homeDir, profileDir);
  const readText = deps.readFileImpl ?? ((filename, encoding) => readFile(filename, encoding));
  const statFile = deps.statImpl ?? ((filename) => stat(filename));
  async function readAt(p) {
    if (!p) return null;
    try {
      if ((await statFile(p.state)).size > 10 * 1024 * 1024) throw fail("install-failed");
      return JSON.parse(await readText(p.state, "utf8"));
    } catch (error) {
      if (error && error.code === "ENOENT") return null;
      throw error && error.code ? error : fail("install-failed");
    }
  }
  async function readJob() {
    if (!paths) return null;
    const job = await readAt(paths);
    if (job) {
      if (!JOB_STATES.includes(String(job.state)) || typeof job.id !== "string") {
        return { id: "corrupt", state: "interrupted", message: "recovery-required", targetVersion: null, requestId: null };
      }
      return { requestId: null, message: null, ...job };
    }
    if (legacyPaths) {
      const legacyJob = await readAt(legacyPaths);
      if (legacyJob) {
        if (!JOB_STATES.includes(String(legacyJob.state)) || typeof legacyJob.id !== "string") {
          return { id: "corrupt", state: "interrupted", message: "recovery-required", targetVersion: null, requestId: null };
        }
        return { requestId: null, message: null, ...legacyJob };
      }
    }
    const lock = await readJsonGuarded(paths.lock, null);
    if (lock) return { id: "locked", state: "interrupted", message: "recovery-required", targetVersion: null, requestId: null };
    if (legacyPaths) {
      const legacyLock = await readJsonGuarded(legacyPaths.lock, null).catch(() => null);
      if (legacyLock) return { id: "locked", state: "interrupted", message: "recovery-required", targetVersion: null, requestId: null };
    }
    return null;
  }
  async function writeJob(job) {
    if (!paths) throw fail("install-failed");
    if (job === null) {
      await unlink(paths.state).catch((error) => {
        if (!error || error.code !== "ENOENT") throw fail("install-failed");
      });
      return;
    }
    await mkdir(paths.directory, { recursive: true, mode: 448 });
    await writeJsonAtomic(paths.state, job);
  }
  async function tryAcquireLock(lockId) {
    if (!paths) return false;
    try {
      await mkdir(paths.directory, { recursive: true, mode: 448 });
      const handle = await open(paths.lock, "wx", 384);
      try {
        await handle.writeFile(JSON.stringify({ id: lockId, pid: process.pid, startedAt: Date.now() }));
      } finally {
        await handle.close();
      }
      return true;
    } catch (error) {
      if (!error || error.code !== "EEXIST") return false;
      try {
        const current = await readJsonGuarded(paths.lock, null);
        const job = await readJsonGuarded(paths.state, null);
        if (!current || job && job.id === current.id) return false;
        await unlink(paths.lock).catch(() => {
        });
        const handle = await open(paths.lock, "wx", 384);
        try {
          await handle.writeFile(JSON.stringify({ id: lockId, pid: process.pid, startedAt: Date.now() }));
        } finally {
          await handle.close();
        }
        return true;
      } catch {
        return false;
      }
    }
  }
  async function releaseLock(lockId) {
    if (!paths) return;
    try {
      const current = await readJsonGuarded(paths.lock, null);
      if (current && current.id === lockId) await unlink(paths.lock).catch(() => {
      });
    } catch {
    }
  }
  async function backupJob(job) {
    if (!paths) throw fail("install-failed");
    const files = {};
    for (const name of SNAPSHOT_FILES) {
      try {
        const filename = join(profileDir, name);
        if ((await stat(filename)).size > 3 * 1024 * 1024) throw fail("install-failed");
        files[name] = await readFile(filename, "utf8");
      } catch (error) {
        if (!error || error.code !== "ENOENT") throw fail("install-failed");
      }
    }
    await mkdir(paths.directory, { recursive: true, mode: 448 });
    await writeJsonAtomic(paths.backup, {
      jobId: job.id,
      previousVersion: job.previousVersion ?? null,
      files
    });
  }
  return { paths, legacyPaths, readJob, writeJob, tryAcquireLock, releaseLock, backupJob };
}
function part(value) {
  return typeof value === "function" ? value() : value;
}
function withExit(error, exitCode) {
  if (typeof exitCode === "number") error.exitCode = exitCode;
  return error;
}
async function sameDir(a, b) {
  if (typeof a !== "string" || typeof b !== "string" || !a || !b) return false;
  try {
    if (resolve(a) === resolve(b)) return true;
  } catch {
    return false;
  }
  try {
    const pair = await Promise.all([realpath(a), realpath(b)]);
    return pair[0] === pair[1];
  } catch {
    return false;
  }
}
async function readManifestAt(directory) {
  try {
    return JSON.parse(await readFile(join(directory, "package.json"), "utf8"));
  } catch {
    return null;
  }
}
async function resolveCliEntry(argv1, deps = {}) {
  const readAt = typeof deps.readManifest === "function" ? deps.readManifest : readManifestAt;
  const realpathImpl = typeof deps.realpath === "function" ? deps.realpath : realpath;
  if (typeof argv1 !== "string" || !argv1 || argv1.includes("\0")) return null;
  let entry = "";
  try {
    entry = await realpathImpl(argv1);
  } catch {
    return null;
  }
  if (typeof entry !== "string" || !entry) return null;
  let directory = dirname(entry);
  while (true) {
    let manifest = null;
    try {
      manifest = await Promise.resolve().then(() => readAt(directory)).catch(() => null);
    } catch {
      manifest = null;
    }
    if (manifest && manifest.name === CLI_PACKAGE_NAME) {
      const bin = manifest.bin;
      const declared = typeof bin === "string" ? bin : bin && bin.dsh;
      if (typeof declared !== "string" || !declared || isAbsolute(declared) || declared.includes("\0")) return null;
      try {
        return await realpathImpl(resolve(directory, declared)) === entry ? entry : null;
      } catch {
        return null;
      }
    }
    const parent = dirname(directory);
    if (parent === directory) return null;
    directory = parent;
  }
}
async function awaitOutcome(handle, timeoutMs) {
  const settled = Promise.resolve(handle.done).then(
    (value) => ({ exitCode: value && typeof value.exitCode === "number" ? value.exitCode : null, timedOut: false }),
    () => ({ exitCode: null, timedOut: true })
  );
  if (!(typeof timeoutMs === "number" && timeoutMs > 0)) return await settled;
  let timer = null;
  const deadline = new Promise((settle) => {
    timer = setTimeout(() => {
      try {
        if (handle && typeof handle.terminate === "function") handle.terminate();
      } catch {
      }
      settle({ exitCode: null, timedOut: true });
    }, timeoutMs);
  });
  try {
    return await Promise.race([settled, deadline]);
  } finally {
    if (timer !== null) {
      try {
        clearTimeout(timer);
      } catch {
      }
    }
  }
}
function emitInstall(parts, recipe, ok, exitCode, durationMs) {
  const log = parts.log;
  if (typeof log !== "function") return;
  try {
    const pluginId = part(parts.pluginId ?? null);
    log("info", "update.install.exec", {
      route: recipe ? recipe.route : "none",
      ok: ok === true,
      exitCode: typeof exitCode === "number" ? exitCode : null,
      durationMs,
      pluginId: typeof pluginId === "string" ? pluginId : null
    });
  } catch {
  }
}
async function runDesktopService(recipe, parts) {
  const service = part(parts.desktopPnpm);
  if (!service || typeof service.runPlugin !== "function") throw fail("install-failed");
  const profiles = part(parts.desktopProfiles);
  const active = profiles && profiles.current ? profiles.current : null;
  const profileDir = part(parts.profileDir);
  if (!active || !active.dir || !profileDir || !await sameDir(active.dir, profileDir)) throw fail("install-failed");
  const handle = service.runPlugin(recipe.pluginArgs, profileDir, void 0);
  if (!handle || !handle.done || typeof handle.done.then !== "function") throw fail("install-failed");
  const outcome = await handle.done;
  const code = outcome && typeof outcome.exitCode === "number" ? outcome.exitCode : null;
  if (code !== 0) throw withExit(fail("install-failed"), code);
  return code;
}
async function runCliProcess(recipe, parts) {
  const executable = part(parts.runtimeExecutable) || (typeof process !== "undefined" ? process.execPath : "");
  const execArgs = part(parts.runtimeExecArgs) ?? (typeof process !== "undefined" && Array.isArray(process.execArgv) ? process.execArgv : []);
  const entry = part(parts.cliEntry) ?? await resolveCliEntry(typeof process !== "undefined" && process.argv ? process.argv[1] : "");
  if (!executable || !entry) throw fail("install-failed");
  const argv = [executable, ...execArgs, entry, "plugin", "--profile", recipe.profileName, ...recipe.pluginArgs];
  const subprocess = part(parts.subprocess);
  if (!subprocess || typeof subprocess.spawn !== "function") throw fail("install-failed");
  const handle = subprocess.spawn({
    argv,
    cwd: part(parts.profileDir) || void 0,
    stdio: INSTALL_STDIO,
    graceMs: TERMINATION_GRACE_MS
  });
  if (!handle || !handle.done || typeof handle.done.then !== "function") throw fail("install-failed");
  const outcome = await awaitOutcome(handle, recipe.timeoutMs);
  if (outcome.timedOut || outcome.exitCode !== 0) throw withExit(fail("install-failed"), outcome.exitCode);
  return outcome.exitCode;
}
function createUpdateExecutor(parts = {}) {
  return async function runInstall(args = {}) {
    const recipe = installRecipe({
      profileName: args.profileName ?? part(parts.profileName ?? null),
      version: String(args.version ?? ""),
      environmentKind: args.environmentKind ?? part(parts.environmentKind ?? "cli"),
      targetPackageName: parts.targetPackageName === void 0 ? void 0 : part(parts.targetPackageName),
      registryUrl: parts.registryUrl === void 0 ? void 0 : part(parts.registryUrl),
      timeoutMs: parts.installTimeoutMs === void 0 ? void 0 : part(parts.installTimeoutMs)
    });
    const startedAt = Date.now();
    let exitCode = null;
    try {
      if (!recipe) throw fail("install-failed");
      exitCode = recipe.route === "desktop-service" ? await runDesktopService(recipe, parts) : await runCliProcess(recipe, parts);
      emitInstall(parts, recipe, true, exitCode, Date.now() - startedAt);
    } catch (error) {
      emitInstall(parts, recipe, false, error?.exitCode ?? exitCode, Date.now() - startedAt);
      throw Object.assign(fail("install-failed"), { debug: String(error?.stack || error) });
    }
  };
}
var LEGACY_SEGMENT, LEGACY_DIR_PLUGIN, JOB_STATES, SNAPSHOT_FILES, CLI_PACKAGE_NAME, INSTALL_STDIO, TERMINATION_GRACE_MS;
var init_store = __esm({
  "node_modules/dsh-plugin-update/dist/store.js"() {
    init_commands();
    init_config();
    LEGACY_SEGMENT = "updates";
    LEGACY_DIR_PLUGIN = LEGACY_PLUGIN_ID;
    JOB_STATES = ["installing", "verifying", "restart-required", "completed", "failed", "interrupted"];
    SNAPSHOT_FILES = ["package.json", "pnpm-lock.yaml", "pnpm-workspace.yaml"];
    CLI_PACKAGE_NAME = "@deepseek-ai/dsh";
    INSTALL_STDIO = { stdin: "ignore", stdout: { maxBytes: 64 * 1024 }, stderr: { maxBytes: 64 * 1024 } };
    TERMINATION_GRACE_MS = 3e3;
  }
});

// node_modules/dsh-plugin-update/dist/reader.js
import { createHash as createHash2, randomUUID as randomUUID2 } from "node:crypto";
import { readFile as readFile2, realpath as realpath2, stat as stat2 } from "node:fs/promises";
import { homedir } from "node:os";
import { basename, dirname as dirname2, isAbsolute as isAbsolute2, join as join2, relative, resolve as resolve2, sep } from "node:path";
import { fileURLToPath } from "node:url";
function inside(directory, filename) {
  const suffix = relative(directory, filename);
  return suffix !== ".." && !suffix.startsWith(`..${sep}`) && !isAbsolute2(suffix);
}
async function readOptional(filename) {
  try {
    return await readFile2(filename, "utf8");
  } catch (error) {
    if (error && error.code === "ENOENT") return "";
    throw error;
  }
}
async function packageAt(directory) {
  const contents = await readFile2(join2(directory, "package.json"), "utf8");
  return { directory: await realpath2(directory), manifest: JSON.parse(contents), contents };
}
async function containingPackage(filename, name) {
  let directory = dirname2(await realpath2(filename));
  while (true) {
    try {
      const found = await packageAt(directory);
      if (found.manifest && found.manifest.name === name) return found;
    } catch (error) {
      if (!error || error.code !== "ENOENT") throw error;
    }
    const parent = dirname2(directory);
    if (parent === directory) return null;
    directory = parent;
  }
}
function profileNameValid(name) {
  return typeof name === "string" && name.length > 0 && Buffer.byteLength(name) <= 255 && !name.startsWith("-") && ![".", "..", "node_modules"].includes(name) && !/[\\/\x00-\x1f\x7f<>:"|?*]/u.test(name);
}
function registrySpec(spec) {
  return typeof spec === "string" && spec.trim().length > 0 && (validVersion2(spec.trim()) || /^[~^>=< ]*[0-9x*][0-9x*./\-_ |~^>=<]*$/u.test(spec.trim()) || /^[A-Za-z][A-Za-z0-9._-]*$/u.test(spec.trim()));
}
async function validPackage(pkg, targetName) {
  if (!pkg || pkg.manifest?.name !== targetName || !validVersion2(pkg.manifest.version)) return false;
  const main = pkg.manifest.main;
  const exportsField = pkg.manifest.exports;
  const dshField = pkg.manifest.dsh;
  const bundle = dshField?.bundle;
  const entries = [main, exportsField?.["./client"], bundle?.patch];
  for (const entry of entries) {
    if (typeof entry !== "string" || !entry || isAbsolute2(entry) || entry.includes("\0")) return false;
    const filename = resolve2(pkg.directory, entry);
    if (!inside(pkg.directory, filename)) return false;
    let target = filename;
    try {
      target = await realpath2(filename);
    } catch {
      return false;
    }
    if (!inside(pkg.directory, target)) return false;
    try {
      if (!(await stat2(target)).isFile()) return false;
    } catch {
      return false;
    }
  }
  return true;
}
function defaultHomeDir(env, osHome) {
  let selected = env && env.DSH_HOME && env.DSH_HOME.trim() ? env.DSH_HOME : join2(osHome, ".dsh");
  if (selected === "~") selected = osHome;
  else if (/^~[\\/]/u.test(selected)) selected = join2(osHome, selected.slice(2));
  return resolve2(selected);
}
function createUpdateReader(options) {
  const runningVersion = options.runningVersion;
  if (typeof runningVersion !== "string" || !runningVersion) {
    throw new Error("[dsh-plugin-update] \u5EFA\u8BFB\u53D6\u5668\u5FC5\u987B\u7ED9\u8FD0\u884C\u7248\u672C runningVersion\uFF08\u8BFB\u5BBF\u4E3B\u81EA\u5E26\u6E05\u5355\uFF09");
  }
  const profileDirInput = options.profileDir;
  if (typeof profileDirInput !== "string" || !isAbsolute2(profileDirInput)) {
    throw new Error("[dsh-plugin-update] \u5EFA\u8BFB\u53D6\u5668\u5FC5\u987B\u7ED9\u7EDD\u5BF9\u8DEF\u5F84\u7684\u4F7F\u7528\u8303\u56F4\u76EE\u5F55 profileDir");
  }
  const pluginId = assertPluginId(options.pluginId);
  const env = options.env ?? process.env;
  const osHome = options.osHome ?? homedir();
  const homeDirDefault = defaultHomeDir(env, osHome);
  const fallbackFetch = globalThis.fetch;
  if (!options.fetchImpl && !fallbackFetch) {
    throw new Error("[dsh-plugin-update] \u5EFA\u8BFB\u53D6\u5668\u5FC5\u987B\u7ED9\u7F51\u7EDC\u5B9E\u73B0 fetchImpl\uFF08\u672C\u673A\u6CA1\u6709\u5168\u5C40 fetch\uFF09");
  }
  const fetchImpl = options.fetchImpl ?? fallbackFetch;
  const now = options.now ?? Date.now;
  const randomId = options.randomId ?? randomUUID2;
  const nodeVersion = options.nodeVersion ?? (typeof process !== "undefined" ? process.versions.node : "");
  const environmentKind = options.environmentKind ?? "cli";
  const targetPackageName = options.targetPackageName ?? "dsh-mattpocock-skills-deck";
  const registryUrl = options.registryUrl ?? "https://registry.npmjs.org/";
  const loadedPackage = containingPackage(fileURLToPath(import.meta.url), targetPackageName).catch(() => null);
  let boundIdentity;
  async function readInstalledReal() {
    const result = {
      profileName: null,
      environmentKind,
      homeDir: null,
      profileDir: null,
      installedVersion: null,
      packageValid: false,
      sourceInstall: false,
      blockedReason: null,
      installationKey: null,
      eligible: false
    };
    const profileName = options.profileName ?? basename(profileDirInput);
    result.profileName = profileName;
    if (!profileNameValid(profileName)) {
      result.blockedReason = "unknown-profile";
      return result;
    }
    let homeDir;
    let profileDir;
    try {
      homeDir = await realpath2(options.homeDir ?? homeDirDefault);
      profileDir = await realpath2(profileDirInput);
    } catch {
      result.blockedReason = "unknown-profile";
      return result;
    }
    result.homeDir = homeDir;
    result.profileDir = profileDir;
    let profile;
    let installed;
    try {
      profile = await packageAt(profileDir);
      installed = await packageAt(join2(profileDir, "node_modules", targetPackageName));
    } catch {
      result.blockedReason = "invalid-installation";
      return result;
    }
    const deps = profile.manifest.dependencies ?? {};
    result.sourceInstall = !registrySpec(deps[targetPackageName]) || !inside(join2(profileDir, "node_modules"), installed.directory);
    result.installedVersion = typeof installed.manifest.version === "string" ? installed.manifest.version : null;
    result.packageValid = await validPackage(installed, targetPackageName);
    const loaded = await loadedPackage;
    const identity = `${homeDir}\0${profileDir}\0${profileName}\0${pluginId}`;
    const sameLoadedPackage = loaded?.directory === installed.directory && loaded?.manifest.version === installed.manifest.version;
    if (boundIdentity === void 0 && sameLoadedPackage && result.packageValid) boundIdentity = identity;
    const stateFiles = await Promise.all(LOCK_FILES.map((name) => readOptional(join2(profileDir, name))));
    try {
      result.installationKey = createHash2("sha256").update(JSON.stringify([identity, profile.contents, installed.directory, installed.contents, ...stateFiles])).digest("hex");
    } catch {
      result.installationKey = null;
    }
    if (boundIdentity !== void 0 && boundIdentity !== identity) result.blockedReason = "installation-changed";
    else if (!sameLoadedPackage && boundIdentity === void 0) result.blockedReason = "installation-changed";
    else if (!result.packageValid) result.blockedReason = "invalid-installation";
    else if (result.sourceInstall) result.blockedReason = "source-install";
    else if (result.installedVersion !== runningVersion) result.blockedReason = "pending-restart";
    result.eligible = !result.blockedReason;
    result.blockedReason = result.blockedReason ?? null;
    return result;
  }
  const readInstalled = options.readInstalled ?? readInstalledReal;
  const core = createUpdateCore({
    readRunningVersion: () => runningVersion,
    readInstalled,
    fetchImpl,
    now,
    randomId,
    nodeVersion,
    checkTimeoutMs: options.checkTimeoutMs,
    confirmationTtlMs: options.confirmationTtlMs,
    targetPackageName,
    registryUrl,
    readJob: options.readJob,
    writeJob: options.writeJob,
    tryAcquireLock: options.tryAcquireLock,
    releaseLock: options.releaseLock,
    backupJob: options.backupJob,
    runInstall: options.runInstall
  });
  return Object.assign(core, { readEnv: readInstalled });
}
var LOCK_FILES;
var init_reader = __esm({
  "node_modules/dsh-plugin-update/dist/reader.js"() {
    init_config();
    init_service();
    LOCK_FILES = ["pnpm-lock.yaml", "pnpm-workspace.yaml", "package-lock.json"];
  }
});

// node_modules/dsh-plugin-update/dist/gate.js
function isNonEmptyString(value) {
  return typeof value === "string" && value.length > 0;
}
function assertStringArray(value, what) {
  if (!Array.isArray(value)) throw new Error("[dsh-plugin-update] \u4E8B\u4EF6\u6E05\u5355 eventList \u975E\u6CD5\uFF1A" + what + " \u5FC5\u987B\u662F\u5B57\u7B26\u4E32\u6570\u7EC4");
  const seen = [];
  for (const item of value) {
    if (!isNonEmptyString(item)) throw new Error("[dsh-plugin-update] \u4E8B\u4EF6\u6E05\u5355 eventList \u975E\u6CD5\uFF1A" + what + " \u91CC\u6709\u7A7A\u5B57\u6BB5\u540D");
    if (seen.indexOf(item) >= 0) throw new Error("[dsh-plugin-update] \u4E8B\u4EF6\u6E05\u5355 eventList \u975E\u6CD5\uFF1A" + what + " \u91CC\u5B57\u6BB5\u540D\u91CD\u590D\uFF1A" + item);
    seen.push(item);
  }
  return seen;
}
function parseEventListManifest(value) {
  if (typeof value === "string") {
    throw new Error("[dsh-plugin-update] \u4E8B\u4EF6\u6E05\u5355 eventList \u975E\u6CD5\uFF1A\u8DEF\u5F84\u5F62\u5F0F\u8BF7\u8C03\u7528\u65B9\u81EA\u5DF1\u8BFB\u6210\u5BF9\u8C61\u518D\u4F20\u5165\uFF0C\u66F4\u65B0\u5305\u4E0D\u8BFB\u76D8");
  }
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    throw new Error("[dsh-plugin-update] \u4E8B\u4EF6\u6E05\u5355 eventList \u975E\u6CD5\uFF1A\u53EA\u6536\u5BF9\u8C61\u5F62\u5F0F\uFF08\u7A7A\u6A21\u677F\u89C1\u5305\u5185\u7684 event-list.template.json\uFF09");
  }
  const input = value;
  if (input["version"] !== 1) {
    throw new Error("[dsh-plugin-update] \u4E8B\u4EF6\u6E05\u5355 eventList \u975E\u6CD5\uFF1Aversion \u73B0\u5728\u53EA\u8BA4 1\uFF08\u6536\u5230 " + JSON.stringify(input["version"]) + "\uFF09");
  }
  const pluginId = assertPluginId(input["pluginId"]);
  const countsRaw = input["counts"];
  if (!countsRaw || typeof countsRaw !== "object" || Array.isArray(countsRaw)) {
    throw new Error("[dsh-plugin-update] \u4E8B\u4EF6\u6E05\u5355 eventList \u975E\u6CD5\uFF1Acounts \u5FC5\u987B\u662F\u542B\u4E09\u7C7B\u8BA1\u6570\u7684\u5BF9\u8C61");
  }
  const countsRecord = countsRaw;
  const counts = { resident: 0, ondemand: 0, selfmon: 0 };
  for (const kind of EVENT_KINDS) {
    const n = countsRecord[kind];
    if (typeof n !== "number" || !isFinite(n) || Math.floor(n) !== n || n < 0) {
      throw new Error("[dsh-plugin-update] \u4E8B\u4EF6\u6E05\u5355 eventList \u975E\u6CD5\uFF1Acounts." + kind + " \u5FC5\u987B\u662F\u975E\u8D1F\u6574\u6570");
    }
    counts[kind] = n;
  }
  const eventsRaw = input["events"];
  if (!eventsRaw || typeof eventsRaw !== "object" || Array.isArray(eventsRaw)) {
    throw new Error("[dsh-plugin-update] \u4E8B\u4EF6\u6E05\u5355 eventList \u975E\u6CD5\uFF1Aevents \u5FC5\u987B\u662F\u4E8B\u4EF6\u540D\u5230\u6761\u76EE\u7684\u5BF9\u8C61");
  }
  const events = {};
  for (const name of Object.keys(eventsRaw)) {
    events[name] = parseEventEntry(name, eventsRaw[name]);
  }
  return { version: 1, pluginId, counts, events };
}
function parseEventEntry(name, value) {
  if (!isNonEmptyString(name)) throw new Error("[dsh-plugin-update] \u4E8B\u4EF6\u6E05\u5355 eventList \u975E\u6CD5\uFF1A\u4E8B\u4EF6\u540D\u4E0D\u80FD\u4E3A\u7A7A");
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    throw new Error("[dsh-plugin-update] \u4E8B\u4EF6\u6E05\u5355 eventList \u975E\u6CD5\uFF1A\u4E8B\u4EF6 " + name + " \u5FC5\u987B\u662F\u5BF9\u8C61");
  }
  const input = value;
  if (EVENT_LEVELS.indexOf(input["level"]) < 0) {
    throw new Error("[dsh-plugin-update] \u4E8B\u4EF6\u6E05\u5355 eventList \u975E\u6CD5\uFF1A\u4E8B\u4EF6 " + name + " \u7684 level \u53EA\u8BB8 error\u3001warn\u3001info\u3001debug");
  }
  if (EVENT_KINDS.indexOf(input["kind"]) < 0) {
    throw new Error("[dsh-plugin-update] \u4E8B\u4EF6\u6E05\u5355 eventList \u975E\u6CD5\uFF1A\u4E8B\u4EF6 " + name + " \u7684 kind \u53EA\u8BB8 resident\u3001ondemand\u3001selfmon");
  }
  for (const key of Object.keys(input)) {
    if (["level", "kind", "fields", "codes", "rules", "guard"].indexOf(key) < 0) {
      throw new Error("[dsh-plugin-update] \u4E8B\u4EF6\u6E05\u5355 eventList \u975E\u6CD5\uFF1A\u4E8B\u4EF6 " + name + " \u6709\u4E0D\u8BA4\u8BC6\u7684\u952E " + key);
    }
  }
  const entry = {
    level: input["level"],
    kind: input["kind"],
    fields: assertStringArray(input["fields"], "\u4E8B\u4EF6 " + name + " \u7684 fields")
  };
  if (input["codes"] !== void 0) entry.codes = assertStringArray(input["codes"], "\u4E8B\u4EF6 " + name + " \u7684 codes");
  if (input["rules"] !== void 0) entry.rules = assertStringArray(input["rules"], "\u4E8B\u4EF6 " + name + " \u7684 rules");
  if (input["guard"] !== void 0) {
    if (typeof input["guard"] !== "string") {
      throw new Error("[dsh-plugin-update] \u4E8B\u4EF6\u6E05\u5355 eventList \u975E\u6CD5\uFF1A\u4E8B\u4EF6 " + name + " \u7684 guard \u5FC5\u987B\u662F\u5B57\u7B26\u4E32");
    }
    entry.guard = input["guard"];
  }
  return entry;
}
function checkEventFields(manifest, eventName, fieldNames) {
  const entry = manifest.events[eventName];
  if (!entry) return { ok: false, unknownEvent: true, unknownFields: [] };
  const allowed = new Set(entry.fields);
  const unknownFields = (Array.isArray(fieldNames) ? fieldNames : []).filter(
    (field) => !allowed.has(field)
  );
  return { ok: unknownFields.length === 0, unknownEvent: false, unknownFields };
}
function checkEventCounts(manifest) {
  const actual = { resident: 0, ondemand: 0, selfmon: 0 };
  for (const name of Object.keys(manifest.events)) {
    actual[manifest.events[name].kind] += 1;
  }
  const problems = [];
  for (const kind of EVENT_KINDS) {
    if (actual[kind] !== manifest.counts[kind]) {
      problems.push(
        "[dsh-plugin-update] \u4E8B\u4EF6\u6E05\u5355\u8BA1\u6570\u5BF9\u4E0D\u4E0A\uFF1A" + kind + " \u7C7B\u5B9E\u9645 " + actual[kind] + " \u6761\uFF0C\u6E05\u5355\u81EA\u62A5 " + manifest.counts[kind] + " \u6761"
      );
    }
  }
  return { ok: problems.length === 0, problems };
}
var EVENT_LEVELS, EVENT_KINDS;
var init_gate = __esm({
  "node_modules/dsh-plugin-update/dist/gate.js"() {
    init_config();
    EVENT_LEVELS = ["error", "warn", "info", "debug"];
    EVENT_KINDS = ["resident", "ondemand", "selfmon"];
  }
});

// node_modules/dsh-plugin-update/dist/host.js
var host_exports = {};
__export(host_exports, {
  __resetSharedUpdateReaderForTests: () => __resetSharedUpdateReaderForTests,
  buildPhoneName: () => buildPhoneName,
  buildPhoneNames: () => buildPhoneNames2,
  checkEventCounts: () => checkEventCounts,
  checkEventFields: () => checkEventFields,
  containingPackage: () => containingPackage,
  createHostUpdate: () => createHostUpdate,
  createUpdateDiskPorts: () => createUpdateDiskPorts,
  createUpdateExecutor: () => createUpdateExecutor,
  defaultHomeDir: () => defaultHomeDir,
  detectEnvironmentKind: () => detectEnvironmentKind,
  parseEventListManifest: () => parseEventListManifest,
  pathsForUpdate: () => pathsForUpdate,
  profileNameValid: () => profileNameValid,
  registrySpec: () => registrySpec,
  resolveCliEntry: () => resolveCliEntry,
  resolveUpdateConfig: () => resolveUpdateConfig
});
import { realpath as realpath3 } from "node:fs/promises";
import { homedir as homedir2 } from "node:os";
import { join as join3, sep as sep2 } from "node:path";
import { fileURLToPath as fileURLToPath2 } from "node:url";
function ctxService(ctx, name) {
  try {
    const get = ctx?.get;
    return typeof get === "function" ? get.call(ctx, name) : void 0;
  } catch {
    return void 0;
  }
}
function detectEnvironmentKind(ctx) {
  const profiles = ctxService(ctx, "desktopProfiles");
  return profiles === void 0 || profiles === null ? "cli" : "desktop";
}
function watchDesktopPnpm(ctx) {
  try {
    if (detectEnvironmentKind(ctx) !== "desktop") return;
    const inject = ctx?.inject;
    if (typeof inject !== "function") return;
    inject.call(ctx, ["desktopPnpm"], (desktopCtx) => {
      try {
        const service = desktopCtx?.desktopPnpm;
        if (service) sharedDesktopPnpm = service;
      } catch {
      }
    });
  } catch {
  }
}
function hash82(s) {
  try {
    const t = String(s || "");
    let h = 5381;
    for (let i = 0; i < t.length; i++) h = (h << 5) + h + t.charCodeAt(i) >>> 0;
    return `0000000${h.toString(16)}`.slice(-8);
  } catch {
    return "00000000";
  }
}
async function inferProfileDir(loaded, homeDirDefault, targetPackageName) {
  try {
    const dir = loaded && loaded.directory ? String(loaded.directory) : "";
    const marker = `${sep2}node_modules${sep2}${targetPackageName}`;
    const at = dir.lastIndexOf(marker);
    if (at > 0) {
      const candidate = dir.slice(0, at);
      try {
        return await realpath3(candidate);
      } catch {
        return candidate;
      }
    }
  } catch {
  }
  return join3(homeDirDefault, "profiles", "web");
}
async function getSharedReader(pluginId, config, overrides = {}) {
  const env = overrides.env ?? process.env;
  const osHome = overrides.osHome ?? homedir2();
  const homeDirDefault = defaultHomeDir(env, osHome);
  const targetPackageName = overrides.targetPackageName ?? config.targetPackageName;
  const loaded = await containingPackage(fileURLToPath2(import.meta.url), targetPackageName).catch(() => null);
  const runningVersion = overrides.runningVersion ?? (loaded && validVersion2(loaded.manifest.version) ? String(loaded.manifest.version) : null);
  if (!runningVersion) throw Object.assign(new Error("unknown-profile"), { code: "unknown-profile" });
  const profileDirInput = overrides.profileDir ?? await inferProfileDir(loaded, homeDirDefault, targetPackageName);
  const homeDirInput = overrides.homeDir ?? config.homeDir ?? homeDirDefault;
  const environmentKind = overrides.environmentKind ?? detectEnvironmentKind(overrides.ctx);
  const checkTimeoutMs = overrides.checkTimeoutMs ?? config.checkTimeoutMs;
  const confirmationTtlMs = overrides.confirmationTtlMs ?? config.confirmationTtlMs;
  const installTimeoutMs = overrides.installTimeoutMs ?? config.installTimeoutMs;
  const registryUrl = overrides.registryUrl ?? config.registryUrl;
  const key = `${pluginId}\0${config.prefix}\0${runningVersion}\0${profileDirInput}\0${overrides.profileName ?? ""}\0${homeDirInput}\0${overrides.runInstall ? "exec" : ""}\0${environmentKind}\0${targetPackageName}`;
  if (sharedReader && sharedReaderKey === key) return sharedReader;
  const disk = overrides.readJob && overrides.writeJob ? null : createUpdateDiskPorts(homeDirInput, pluginId, profileDirInput);
  const defaultRun = createUpdateExecutor({
    profileName: overrides.profileName ?? null,
    environmentKind,
    profileDir: profileDirInput,
    subprocess: () => overrides.subprocess ?? ctxService(overrides.ctx, "subprocess"),
    desktopPnpm: () => overrides.desktopPnpm ?? sharedDesktopPnpm,
    desktopProfiles: () => overrides.desktopProfiles ?? ctxService(overrides.ctx, "desktopProfiles"),
    runtimeExecutable: () => overrides.runtimeExecutable,
    runtimeExecArgs: () => overrides.runtimeExecArgs,
    cliEntry: () => overrides.cliEntry,
    targetPackageName,
    registryUrl,
    installTimeoutMs,
    pluginId,
    log: emitInstallLog
  });
  sharedReader = createUpdateReader({
    runningVersion,
    profileDir: profileDirInput,
    pluginId,
    profileName: overrides.profileName ?? void 0,
    homeDir: overrides.homeDir,
    env,
    osHome,
    fetchImpl: overrides.fetchImpl,
    now: overrides.now,
    randomId: overrides.randomId,
    nodeVersion: overrides.nodeVersion,
    environmentKind,
    targetPackageName,
    registryUrl,
    checkTimeoutMs,
    confirmationTtlMs,
    readInstalled: overrides.readInstalled,
    readJob: overrides.readJob,
    writeJob: overrides.writeJob,
    tryAcquireLock: overrides.tryAcquireLock ?? disk?.tryAcquireLock,
    releaseLock: overrides.releaseLock ?? disk?.releaseLock,
    backupJob: overrides.backupJob ?? disk?.backupJob,
    runInstall: overrides.runInstall ?? defaultRun
  });
  sharedReaderKey = key;
  return sharedReader;
}
function toUpdateErrorPayload(error) {
  const code = error && typeof error.code === "string" ? String(error.code) : "";
  const known = [
    "check-failed",
    "invalid-release",
    "check-expired",
    "update-busy",
    "install-failed",
    "unknown-profile",
    "source-install",
    "invalid-installation",
    "installation-changed",
    "pending-restart",
    "incompatible-node",
    "registry-conflict",
    "recovery-required"
  ];
  if (known.includes(code)) return { error: code, errorKind: code };
  return { error: "check-failed", errorKind: "internal" };
}
function manualOfEnv(env, snapshot, config) {
  try {
    return manualCommand({
      profileName: env?.profileName ?? null,
      latestVersion: snapshot?.latestVersion ?? null,
      installedVersion: snapshot?.installedVersion ?? null,
      runningVersion: String(snapshot?.runningVersion ?? ""),
      jobTargetVersion: snapshot?.job?.targetVersion ?? null,
      blockedReason: snapshot?.blockedReason ?? null,
      sourceInstall: env?.sourceInstall === true,
      targetPackageName: config.targetPackageName,
      registryUrl: config.registryUrl
    });
  } catch {
    return null;
  }
}
async function snapWithManual(reader, snapshot, config) {
  try {
    return { snapshot, manual: manualOfEnv(await reader.readEnv(), snapshot, config) };
  } catch {
    return { snapshot, manual: null };
  }
}
function emitInstallLog(level, event, fields) {
  try {
    if (phoneLogCtx && typeof phoneLogCtx.fire === "function") phoneLogCtx.fire(level, event, fields);
  } catch {
  }
}
function loggedPhone(method, kind, pluginId, fn) {
  return async function(args) {
    const t0 = Date.now();
    const emit = (level, event, fields) => {
      try {
        if (phoneLogCtx && typeof phoneLogCtx.fire === "function") phoneLogCtx.fire(level, event, fields);
      } catch {
      }
    };
    try {
      const out = await fn(args);
      const snapshot = out && out.snapshot ? out.snapshot : out;
      emit("info", "host.call", { method, latencyMs: Date.now() - t0, ok: true, kind, pluginId });
      return { ok: true, snapshot, manual: out && out.snapshot ? out.manual ?? null : null, receipt: out && out.receipt ? out.receipt : null };
    } catch (error) {
      const payload = toUpdateErrorPayload(error);
      emit("warn", "host.call.fail", { method, kind, errorHash: hash82(String(error?.message || payload.error)), pluginId });
      return { ok: false, ...payload };
    }
  };
}
function createHostUpdate(deps = {}, configInput) {
  const config = resolveUpdateConfig(configInput);
  const pluginId = config.pluginId;
  phoneLogCtx = deps.logCtx ?? phoneLogCtx;
  const ctx = deps.ctx ?? null;
  if (deps.desktopPnpm) sharedDesktopPnpm = deps.desktopPnpm;
  else watchDesktopPnpm(ctx);
  const readerOverrides = { ...deps.readerOverrides ?? {}, ctx };
  const phoneNames = buildPhoneNames2(config.prefix);
  async function readStatus(args) {
    const reader = await getSharedReader(pluginId, config, {
      ...readerOverrides,
      profileDir: args && args.profileDir ? String(args.profileDir) : readerOverrides.profileDir
    });
    return snapWithManual(reader, await reader.status(), config);
  }
  async function readCheck(args) {
    const reader = await getSharedReader(pluginId, config, {
      ...readerOverrides,
      profileDir: args && args.profileDir ? String(args.profileDir) : readerOverrides.profileDir
    });
    const result = await reader.check();
    const withManual = await snapWithManual(reader, result.snapshot, config);
    return { snapshot: withManual.snapshot, manual: withManual.manual, receipt: result.receipt ?? null };
  }
  async function runInstall(args) {
    const checkId = args && typeof args.checkId === "string" ? args.checkId : "";
    const requestId = args && typeof args.requestId === "string" ? args.requestId : "";
    const reader = await getSharedReader(pluginId, config, {
      ...readerOverrides,
      profileDir: args && args.profileDir ? String(args.profileDir) : readerOverrides.profileDir
    });
    return snapWithManual(reader, await reader.install({ checkId, requestId }), config);
  }
  const handlers = {
    [phoneNames.updateStatus]: loggedPhone(phoneNames.updateStatus, "update-status", pluginId, readStatus),
    [phoneNames.updateCheck]: loggedPhone(phoneNames.updateCheck, "update-check", pluginId, readCheck),
    [phoneNames.updateInstall]: loggedPhone(phoneNames.updateInstall, "update-install", pluginId, runInstall)
  };
  return { phoneNames, handlers };
}
function __resetSharedUpdateReaderForTests() {
  sharedReader = null;
  sharedReaderKey = "";
  sharedDesktopPnpm = null;
}
var sharedReader, sharedReaderKey, sharedDesktopPnpm, phoneLogCtx;
var init_host = __esm({
  "node_modules/dsh-plugin-update/dist/host.js"() {
    init_config();
    init_commands();
    init_service();
    init_store();
    init_reader();
    init_config();
    init_gate();
    init_reader();
    init_store();
    sharedReader = null;
    sharedReaderKey = "";
    sharedDesktopPnpm = null;
    phoneLogCtx = null;
  }
});

// src/update/gen/updateClient.derived.js
var DEFAULT_CONFIRMATION_TTL_MS = 10 * 6e4;
var DEFAULT_INSTALL_TIMEOUT_MS = 15 * 6e4;
var DEFAULT_PANEL_POLL_MS = 1e3;
var MIN_PANEL_POLL_MS = 250;
function assertPrefix(value, role) {
  if (typeof value !== "string" || value.length === 0) {
    throw new Error("[dsh-plugin-update] " + role + " \u975E\u6CD5\uFF1A\u987B\u4E3A\u975E\u7A7A\u5B57\u7B26\u4E32\uFF08\u6536\u5230 " + JSON.stringify(value) + "\uFF09");
  }
  if (value.includes(".") || value.includes("/") || value.includes("\\") || /\s/.test(value)) {
    throw new Error("[dsh-plugin-update] " + role + " \u975E\u6CD5\uFF1A\u4E0D\u5F97\u542B\u6709\u70B9\u3001\u8DEF\u5F84\u5206\u9694\u7B26\u6216\u7A7A\u767D\uFF08\u6536\u5230 " + JSON.stringify(value) + "\uFF09");
  }
  return value;
}
function buildPhoneNames(prefix) {
  const checked = assertPrefix(prefix, "\u7535\u8BDD\u540D\u524D\u7F00 prefix");
  return {
    updateStatus: checked + ".updateStatus",
    updateCheck: checked + ".updateCheck",
    updateInstall: checked + ".updateInstall"
  };
}
var INSTALL_TIMEOUT_MS = 15 * 6e4;
var CLIENT_POLL = {
  defaultMs: DEFAULT_PANEL_POLL_MS,
  minMs: MIN_PANEL_POLL_MS
};
function buildClientPhoneNames(prefix) {
  return buildPhoneNames(prefix);
}
var UPD_PHONE_NAMES = buildClientPhoneNames("prompt");
var UPD_POLL_MS = CLIENT_POLL.defaultMs;
var UPD_POLL_MIN_MS = CLIENT_POLL.minMs;
var UPD_STATUS = UPD_PHONE_NAMES.updateStatus;
var UPD_CHECK = UPD_PHONE_NAMES.updateCheck;
var UPD_INSTALL = UPD_PHONE_NAMES.updateInstall;

// src/update/bridge.ts
var UPDATE_STATUS_PATH = "/_dsh/dsh-prompt/update/status";
var UPDATE_CHECK_PATH = "/_dsh/dsh-prompt/update/check";
var UPDATE_INSTALL_PATH = "/_dsh/dsh-prompt/update/install";

// src/update/host/hash.ts
function hash8(value) {
  const text = String(value ?? "");
  let h = 5381;
  for (let i = 0; i < text.length; i++) h = (h << 5) + h + text.charCodeAt(i) >>> 0;
  return ("0000000" + h.toString(16)).slice(-8);
}

// src/update/host/safe-values.ts
var PLUGIN_ID = "dsh-prompt";
var PHONE_PREFIX = "prompt";
var UPDATE_ROUTE_FAMILY = UPDATE_STATUS_PATH.slice(0, UPDATE_STATUS_PATH.lastIndexOf("/"));
var SAFE_METHODS = [
  PHONE_PREFIX + ".updateStatus",
  PHONE_PREFIX + ".updateCheck",
  PHONE_PREFIX + ".updateInstall"
];
var SAFE_KINDS = ["update-status", "update-check", "update-install", "phone-failed", "unknown-phone"];
var SAFE_EXEC_ROUTES = ["cli-process", "desktop-service", "none"];
var SAFE_UPDATE_ROUTES = [
  UPDATE_STATUS_PATH,
  UPDATE_CHECK_PATH,
  UPDATE_INSTALL_PATH,
  UPDATE_ROUTE_FAMILY
];
var SAFE_REASONS = [
  "check-failed",
  "invalid-release",
  "check-expired",
  "update-busy",
  "install-failed",
  "unknown-profile",
  "source-install",
  "invalid-installation",
  "installation-changed",
  "pending-restart",
  "incompatible-node",
  "registry-conflict",
  "recovery-required",
  "unknown-event",
  "unknown-phone",
  "phone-failed",
  "dep-load-fail",
  "capability-degraded",
  "capability-build-fail"
];
var SAFE_FIELD_ENUM = {
  "host.call": { method: SAFE_METHODS, kind: SAFE_KINDS, pluginId: [PLUGIN_ID], errorHash: "hash8" },
  "host.call.fail": { method: SAFE_METHODS, kind: SAFE_KINDS, pluginId: [PLUGIN_ID], errorHash: "hash8" },
  "update.install.exec": { route: SAFE_EXEC_ROUTES, pluginId: [PLUGIN_ID] },
  "update.route.fail": { route: SAFE_UPDATE_ROUTES, reason: SAFE_REASONS, errorHash: "hash8" }
};
var SAFE_VALUE_RE = /^[A-Za-z0-9._:\/-]{0,64}$/;
function toText(value) {
  try {
    const json = JSON.stringify(value);
    return typeof json === "string" ? json : String(value);
  } catch (e) {
    return String(value);
  }
}
function allowedBy(enumSpec, text) {
  if (enumSpec === "hash8") return /^[0-9a-f]{8}$/.test(text);
  return enumSpec.indexOf(text) >= 0;
}
function safeValue(event, key, value) {
  if (value === void 0 || value === null) return value;
  if (typeof value === "number" || typeof value === "boolean") return value;
  const text = typeof value === "string" ? value : toText(value);
  const enumSpec = SAFE_FIELD_ENUM[event]?.[key];
  if (enumSpec !== void 0) return allowedBy(enumSpec, text) ? text : hash8(text);
  return SAFE_VALUE_RE.test(text) ? text : hash8(text);
}
function safeFields(event, fields) {
  const out = { ...fields };
  for (const key of Object.keys(out)) out[key] = safeValue(event, key, out[key]);
  return out;
}

// src/update/host/bridge-log.ts
var DEFAULT_RELOG_FLOOR_MS = 6e4;
function failKeyOf(method, kind) {
  return method + "\0" + kind;
}
function createBridgeLog(logReady, clock) {
  let cap = null;
  const now = typeof clock?.now === "function" ? clock.now : () => Date.now();
  const relogFloorMs = typeof clock?.relogFloorMs === "number" && clock.relogFloorMs >= 0 ? clock.relogFloorMs : DEFAULT_RELOG_FLOOR_MS;
  let unknownReported = false;
  const failedStates = /* @__PURE__ */ new Map();
  if (logReady && typeof logReady.then === "function") {
    logReady.then(
      (ready) => {
        cap = ready && typeof ready.log === "function" ? ready : null;
      },
      () => {
        cap = null;
      }
    );
  }
  function noteFail(method, kind, causeHash) {
    const key = failKeyOf(method, kind);
    const cause = String(causeHash);
    const at = now();
    const entry = failedStates.get(key);
    if (!entry) {
      failedStates.set(key, { reported: /* @__PURE__ */ new Set([cause]), pending: [], lastLogAt: at });
      return true;
    }
    const head = entry.pending[0];
    if (head !== void 0 && head.hash === cause) {
      if (at - entry.lastLogAt < relogFloorMs) return false;
      entry.pending.shift();
      entry.reported.add(cause);
      entry.lastLogAt = at;
      return true;
    }
    if (entry.reported.has(cause)) return false;
    if (entry.pending.some((p) => p.hash === cause)) return false;
    if (at - entry.lastLogAt >= relogFloorMs) {
      entry.reported.add(cause);
      entry.lastLogAt = at;
      return true;
    }
    entry.pending.push({ hash: cause, at });
    return flushPendingFail(entry);
  }
  function flushPendingFail(entry) {
    const head = entry.pending[0];
    if (!head) return false;
    if (now() - head.at < relogFloorMs) return false;
    entry.pending.shift();
    entry.reported.add(head.hash);
    entry.lastLogAt = now();
    return true;
  }
  function clearFails(method) {
    const prefix = failKeyOf(method, "");
    for (const [key, state] of failedStates) {
      if (!key.startsWith(prefix)) continue;
      state.reported = /* @__PURE__ */ new Set();
      state.pending = [];
    }
  }
  return {
    fire(level, event, fields) {
      try {
        if (!cap) return;
        const f = fields ?? {};
        switch (String(event ?? "")) {
          case "host.call": {
            const safe = safeFields("host.call", f);
            if (safe.ok === true) clearFails(String(safe.method ?? ""));
            cap.log("host.call", { ...safe });
            return;
          }
          case "host.call.fail": {
            const safe = safeFields("host.call.fail", f);
            const causeHash = hash8(String(f.errorHash ?? ""));
            if (!noteFail(String(safe.method ?? ""), String(safe.kind ?? ""), causeHash)) return;
            cap.log("host.call.fail", { ...safe });
            return;
          }
          case "update.install.exec": {
            const safe = safeFields("update.install.exec", f);
            cap.log("update.install.exec", { ...safe });
            return;
          }
          default:
            if (unknownReported) return;
            unknownReported = true;
            cap.log("update.route.fail", {
              route: UPDATE_ROUTE_FAMILY,
              reason: "unknown-event",
              errorHash: hash8(String(event ?? ""))
            });
        }
      } catch (e) {
      }
    }
  };
}

// src/update/host/index.ts
var PLUGIN_ID2 = "dsh-prompt";
var PHONE_PREFIX2 = "prompt";
var TARGET_PACKAGE_NAME = "dsh-prompt";
var UNAVAILABLE = "update-capability-unavailable";
var SNAPSHOT_FIELDS = [
  "runningVersion",
  // 正在跑的版本
  "installedVersion",
  // 磁盘上装着的版本（与上一条不同即待重启）
  "latestVersion",
  // 官方源上的最新版本（没查过就是 null）
  "canInstall",
  // 现在能不能装
  "blockedReason",
  // 装不了的原因（八种之一，能装时为 null）
  "job"
  // 进行中/上次的安装任务
];
async function createUpdateCapability(options = {}) {
  let mod = options.hostUpdate ?? await Promise.resolve().then(() => (init_host(), host_exports)).catch((e) => e);
  if (mod instanceof Error) {
    return degradedCapability(`dep-load-fail: ${mod.message}`, options.onFallback);
  }
  let update;
  const bridgeLog = createBridgeLog(options.logReady, { now: options.now, relogFloorMs: options.relogFloorMs });
  try {
    update = mod.createHostUpdate(
      { ctx: options.ctx ?? null, logCtx: bridgeLog },
      {
        pluginId: PLUGIN_ID2,
        prefix: PHONE_PREFIX2,
        targetPackageName: TARGET_PACKAGE_NAME
        // 其余全走包默认值（官方源、家目录、超时、凭证有效期、轮询间隔），本票一个都不动。
      }
    );
  } catch (e) {
    return degradedCapability(String(e?.message || e), options.onFallback);
  }
  const phoneNames = update.phoneNames;
  const phones = {
    status: phoneNames.updateStatus,
    check: phoneNames.updateCheck,
    install: phoneNames.updateInstall
  };
  const routes = {
    [UPDATE_STATUS_PATH]: phones.status,
    [UPDATE_CHECK_PATH]: phones.check,
    [UPDATE_INSTALL_PATH]: phones.install
  };
  function logPhoneFail(method, kind, message) {
    bridgeLog.fire("warn", "host.call.fail", {
      method,
      kind,
      errorHash: hash8(message),
      pluginId: PLUGIN_ID2
    });
  }
  return {
    ok: true,
    phoneNames: { ...phoneNames },
    paths: { status: UPDATE_STATUS_PATH, check: UPDATE_CHECK_PATH, install: UPDATE_INSTALL_PATH },
    /** 快照六字段名（只读常量，给回归脚本与将来的面板对账用）。 */
    snapshotFields: SNAPSHOT_FIELDS,
    /**
     * 电话调用口：路由按 URL 找人，这里按电话名找函数。回包形状 = 更新包 loggedPhone 的形状
     * （`{ ok, snapshot, manual, receipt }`）。
     */
    async runRoute(path, args) {
      const phone = routes[path];
      if (phone === void 0) {
        logPhoneFail(path, "unknown-phone", `no update phone for ${path}`);
        return failed("unknown-phone", `no update phone for ${path}`);
      }
      try {
        return await update.handlers[phone](args ?? {});
      } catch (e) {
        const message = String(e?.message || e);
        logPhoneFail(String(phone), "phone-failed", message);
        return failed("phone-failed", message);
      }
    }
  };
}
function failed(error, errorKind) {
  return { ok: false, error, errorKind };
}
function degradedCapability(reason, onFallback) {
  try {
    if (typeof onFallback === "function") onFallback(reason);
  } catch (e) {
  }
  return {
    ok: false,
    reason,
    phoneNames: {},
    paths: { status: UPDATE_STATUS_PATH, check: UPDATE_CHECK_PATH, install: UPDATE_INSTALL_PATH },
    snapshotFields: SNAPSHOT_FIELDS,
    async runRoute() {
      return failed(UNAVAILABLE, reason);
    }
  };
}
export {
  PHONE_PREFIX2 as PHONE_PREFIX,
  PLUGIN_ID2 as PLUGIN_ID,
  SNAPSHOT_FIELDS,
  TARGET_PACKAGE_NAME,
  createUpdateCapability
};
