// AUTO-GENERATED by node scripts/update/build-host.mjs — DO NOT EDIT. Source: src/update/host/index.ts

// src/update/gen/updateClient.derived.js
var DEFAULT_CONFIRMATION_TTL_MS = 10 * 6e4;
var DEFAULT_INSTALL_TIMEOUT_MS = 15 * 6e4;
var DEFAULT_PANEL_POLL_MS = 1e3;
var MIN_PANEL_POLL_MS = 250;
function assertPrefix(value, role) {
  if (typeof value !== "string" || value.length === 0) {
    throw new Error("[dsh-plugin-update] " + role + " \u975E\u6CD5\uFF1A\u987B\u4E3A\u975E\u7A7A\u5B57\u7B26\u4E32\uFF08\u6536\u5230 " + JSON.stringify(value) + "\uFF09");
  }
  if (value.includes(".") || value.includes("/") || value.includes("\\") || /\s/.test(value)) {
    throw new Error("[dsh-plugin-update] " + role + " \u975E\u6CD5\uFF1A\u4E0D\u5F97\u542B\u6709\u70B9\u3001\u8DEF\u5F84\u5206\u9694\u7B26\u6216\u7A7A\u767D\uFF08\u6536\u5230 " + JSON.stringify(value) + "\uFF09");
  }
  return value;
}
function buildPhoneNames(prefix) {
  const checked = assertPrefix(prefix, "\u7535\u8BDD\u540D\u524D\u7F00 prefix");
  return {
    updateStatus: checked + ".updateStatus",
    updateCheck: checked + ".updateCheck",
    updateInstall: checked + ".updateInstall"
  };
}
var INSTALL_TIMEOUT_MS = 15 * 6e4;
var CLIENT_POLL = {
  defaultMs: DEFAULT_PANEL_POLL_MS,
  minMs: MIN_PANEL_POLL_MS
};
function buildClientPhoneNames(prefix) {
  return buildPhoneNames(prefix);
}
var UPD_PHONE_NAMES = buildClientPhoneNames("prompt");
var UPD_POLL_MS = CLIENT_POLL.defaultMs;
var UPD_POLL_MIN_MS = CLIENT_POLL.minMs;
var UPD_STATUS = UPD_PHONE_NAMES.updateStatus;
var UPD_CHECK = UPD_PHONE_NAMES.updateCheck;
var UPD_INSTALL = UPD_PHONE_NAMES.updateInstall;

// src/update/bridge.ts
var UPDATE_STATUS_PATH = "/_dsh/dsh-prompt/update/status";
var UPDATE_CHECK_PATH = "/_dsh/dsh-prompt/update/check";
var UPDATE_INSTALL_PATH = "/_dsh/dsh-prompt/update/install";

// src/update/host/hash.ts
function hash8(value) {
  const text = String(value ?? "");
  let h = 5381;
  for (let i = 0; i < text.length; i++) h = (h << 5) + h + text.charCodeAt(i) >>> 0;
  return ("0000000" + h.toString(16)).slice(-8);
}

// src/update/host/safe-values.ts
var PLUGIN_ID = "dsh-prompt";
var PHONE_PREFIX = "prompt";
var UPDATE_ROUTE_FAMILY = UPDATE_STATUS_PATH.slice(0, UPDATE_STATUS_PATH.lastIndexOf("/"));
var SAFE_METHODS = [
  PHONE_PREFIX + ".updateStatus",
  PHONE_PREFIX + ".updateCheck",
  PHONE_PREFIX + ".updateInstall"
];
var SAFE_KINDS = ["update-status", "update-check", "update-install", "phone-failed", "unknown-phone"];
var SAFE_EXEC_ROUTES = ["cli-process", "desktop-service", "none"];
var SAFE_UPDATE_ROUTES = [
  UPDATE_STATUS_PATH,
  UPDATE_CHECK_PATH,
  UPDATE_INSTALL_PATH,
  UPDATE_ROUTE_FAMILY
];
var SAFE_REASONS = [
  "check-failed",
  "invalid-release",
  "check-expired",
  "update-busy",
  "install-failed",
  "unknown-profile",
  "source-install",
  "invalid-installation",
  "installation-changed",
  "pending-restart",
  "incompatible-node",
  "registry-conflict",
  "recovery-required",
  "unknown-event",
  "unknown-phone",
  "phone-failed",
  "dep-load-fail",
  "capability-degraded",
  "capability-build-fail"
];
var SAFE_FIELD_ENUM = {
  "host.call": { method: SAFE_METHODS, kind: SAFE_KINDS, pluginId: [PLUGIN_ID], errorHash: "hash8" },
  "host.call.fail": { method: SAFE_METHODS, kind: SAFE_KINDS, pluginId: [PLUGIN_ID], errorHash: "hash8" },
  "update.install.exec": { route: SAFE_EXEC_ROUTES, pluginId: [PLUGIN_ID] },
  "update.route.fail": { route: SAFE_UPDATE_ROUTES, reason: SAFE_REASONS, errorHash: "hash8" }
};
var SAFE_VALUE_RE = /^[A-Za-z0-9._:\/-]{0,64}$/;
function toText(value) {
  try {
    const json = JSON.stringify(value);
    return typeof json === "string" ? json : String(value);
  } catch (e) {
    return String(value);
  }
}
function allowedBy(enumSpec, text) {
  if (enumSpec === "hash8") return /^[0-9a-f]{8}$/.test(text);
  return enumSpec.indexOf(text) >= 0;
}
function safeValue(event, key, value) {
  if (value === void 0 || value === null) return value;
  if (typeof value === "number" || typeof value === "boolean") return value;
  const text = typeof value === "string" ? value : toText(value);
  const enumSpec = SAFE_FIELD_ENUM[event]?.[key];
  if (enumSpec !== void 0) return allowedBy(enumSpec, text) ? text : hash8(text);
  return SAFE_VALUE_RE.test(text) ? text : hash8(text);
}
function safeFields(event, fields) {
  const out = { ...fields };
  for (const key of Object.keys(out)) out[key] = safeValue(event, key, out[key]);
  return out;
}

// src/update/host/bridge-log.ts
var DEFAULT_RELOG_FLOOR_MS = 6e4;
function failKeyOf(method, kind) {
  return method + "\0" + kind;
}
function createBridgeLog(logReady, clock) {
  let cap = null;
  const now = typeof clock?.now === "function" ? clock.now : () => Date.now();
  const relogFloorMs = typeof clock?.relogFloorMs === "number" && clock.relogFloorMs >= 0 ? clock.relogFloorMs : DEFAULT_RELOG_FLOOR_MS;
  let unknownReported = false;
  const failedStates = /* @__PURE__ */ new Map();
  if (logReady && typeof logReady.then === "function") {
    logReady.then(
      (ready) => {
        cap = ready && typeof ready.log === "function" ? ready : null;
      },
      () => {
        cap = null;
      }
    );
  }
  function noteFail(method, kind, causeHash) {
    const key = failKeyOf(method, kind);
    const cause = String(causeHash);
    const at = now();
    const entry = failedStates.get(key);
    if (!entry) {
      failedStates.set(key, { reported: /* @__PURE__ */ new Set([cause]), pending: [], lastLogAt: at });
      return true;
    }
    const head = entry.pending[0];
    if (head !== void 0 && head.hash === cause) {
      if (at - entry.lastLogAt < relogFloorMs) return false;
      entry.pending.shift();
      entry.reported.add(cause);
      entry.lastLogAt = at;
      return true;
    }
    if (entry.reported.has(cause)) return false;
    if (entry.pending.some((p) => p.hash === cause)) return false;
    if (at - entry.lastLogAt >= relogFloorMs) {
      entry.reported.add(cause);
      entry.lastLogAt = at;
      return true;
    }
    entry.pending.push({ hash: cause, at });
    return flushPendingFail(entry);
  }
  function flushPendingFail(entry) {
    const head = entry.pending[0];
    if (!head) return false;
    if (now() - head.at < relogFloorMs) return false;
    entry.pending.shift();
    entry.reported.add(head.hash);
    entry.lastLogAt = now();
    return true;
  }
  function clearFails(method) {
    const prefix = failKeyOf(method, "");
    for (const [key, state] of failedStates) {
      if (!key.startsWith(prefix)) continue;
      state.reported = /* @__PURE__ */ new Set();
      state.pending = [];
    }
  }
  return {
    fire(level, event, fields) {
      try {
        if (!cap) return;
        const f = fields ?? {};
        switch (String(event ?? "")) {
          case "host.call": {
            const safe = safeFields("host.call", f);
            if (safe.ok === true) clearFails(String(safe.method ?? ""));
            cap.log("host.call", { ...safe });
            return;
          }
          case "host.call.fail": {
            const safe = safeFields("host.call.fail", f);
            const causeHash = hash8(String(f.errorHash ?? ""));
            if (!noteFail(String(safe.method ?? ""), String(safe.kind ?? ""), causeHash)) return;
            cap.log("host.call.fail", { ...safe });
            return;
          }
          case "update.install.exec": {
            const safe = safeFields("update.install.exec", f);
            cap.log("update.install.exec", { ...safe });
            return;
          }
          default:
            if (unknownReported) return;
            unknownReported = true;
            cap.log("update.route.fail", {
              route: UPDATE_ROUTE_FAMILY,
              reason: "unknown-event",
              errorHash: hash8(String(event ?? ""))
            });
        }
      } catch (e) {
      }
    }
  };
}

// src/update/host/index.ts
var PLUGIN_ID2 = "dsh-prompt";
var PHONE_PREFIX2 = "prompt";
var TARGET_PACKAGE_NAME = "dsh-prompt";
var UNAVAILABLE = "update-capability-unavailable";
var SNAPSHOT_FIELDS = [
  "runningVersion",
  // 正在跑的版本
  "installedVersion",
  // 磁盘上装着的版本（与上一条不同即待重启）
  "latestVersion",
  // 官方源上的最新版本（没查过就是 null）
  "canInstall",
  // 现在能不能装
  "blockedReason",
  // 装不了的原因（八种之一，能装时为 null）
  "job"
  // 进行中/上次的安装任务
];
async function createUpdateCapability(options = {}) {
  let mod = options.hostUpdate ?? await import("dsh-plugin-update").catch((e) => e);
  if (mod instanceof Error) {
    return degradedCapability(`dep-load-fail: ${mod.message}`, options.onFallback);
  }
  let update;
  const bridgeLog = createBridgeLog(options.logReady, { now: options.now, relogFloorMs: options.relogFloorMs });
  try {
    update = mod.createHostUpdate(
      { ctx: options.ctx ?? null, logCtx: bridgeLog },
      {
        pluginId: PLUGIN_ID2,
        prefix: PHONE_PREFIX2,
        targetPackageName: TARGET_PACKAGE_NAME
        // 其余全走包默认值（官方源、家目录、超时、凭证有效期、轮询间隔），本票一个都不动。
      }
    );
  } catch (e) {
    return degradedCapability(String(e?.message || e), options.onFallback);
  }
  const phoneNames = update.phoneNames;
  const phones = {
    status: phoneNames.updateStatus,
    check: phoneNames.updateCheck,
    install: phoneNames.updateInstall
  };
  const routes = {
    [UPDATE_STATUS_PATH]: phones.status,
    [UPDATE_CHECK_PATH]: phones.check,
    [UPDATE_INSTALL_PATH]: phones.install
  };
  function logPhoneFail(method, kind, message) {
    bridgeLog.fire("warn", "host.call.fail", {
      method,
      kind,
      errorHash: hash8(message),
      pluginId: PLUGIN_ID2
    });
  }
  return {
    ok: true,
    phoneNames: { ...phoneNames },
    paths: { status: UPDATE_STATUS_PATH, check: UPDATE_CHECK_PATH, install: UPDATE_INSTALL_PATH },
    /** 快照六字段名（只读常量，给回归脚本与将来的面板对账用）。 */
    snapshotFields: SNAPSHOT_FIELDS,
    /**
     * 电话调用口：路由按 URL 找人，这里按电话名找函数。回包形状 = 更新包 loggedPhone 的形状
     * （`{ ok, snapshot, manual, receipt }`）。
     */
    async runRoute(path, args) {
      const phone = routes[path];
      if (phone === void 0) {
        logPhoneFail(path, "unknown-phone", `no update phone for ${path}`);
        return failed("unknown-phone", `no update phone for ${path}`);
      }
      try {
        return await update.handlers[phone](args ?? {});
      } catch (e) {
        const message = String(e?.message || e);
        logPhoneFail(String(phone), "phone-failed", message);
        return failed("phone-failed", message);
      }
    }
  };
}
function failed(error, errorKind) {
  return { ok: false, error, errorKind };
}
function degradedCapability(reason, onFallback) {
  try {
    if (typeof onFallback === "function") onFallback(reason);
  } catch (e) {
  }
  return {
    ok: false,
    reason,
    phoneNames: {},
    paths: { status: UPDATE_STATUS_PATH, check: UPDATE_CHECK_PATH, install: UPDATE_INSTALL_PATH },
    snapshotFields: SNAPSHOT_FIELDS,
    async runRoute() {
      return failed(UNAVAILABLE, reason);
    }
  };
}
export {
  PHONE_PREFIX2 as PHONE_PREFIX,
  PLUGIN_ID2 as PLUGIN_ID,
  SNAPSHOT_FIELDS,
  TARGET_PACKAGE_NAME,
  createUpdateCapability
};
