/**
 * 宿主半打包（#39）：src/update/host/index.ts → lib/update.js
 *
 * 为什么要有这一步：客户端半走 tsdown（`lib/client.js`），宿主半却是检入的 JS；更新能力要在
 * 宿主里 import 第三方包 `dsh-plugin-update`，还带一层 `../bridge.js` 的类型，所以给它一条
 * 最小构建步骤（只用 esbuild，不引第二套打包器）。源码住 `src/update/host/`，`lib/` 只放产物；
 * 产物与 `lib/index.js` / `lib/log/index.js` 一样入库（用户从 npm 装到的就是这个 lib/）。
 *
 * `dsh-plugin-update` 保持外部（externals）：运行时按包名 import，走 profile 的 node_modules，
 * 升级只改 package.json 一处版本号；打死进产物会让两处版本各自漂移（wf 就吃了这个亏）。
 */
import { build } from 'esbuild'
import { fileURLToPath } from 'node:url'

// 入口 / 产物 / 工作目录都钉在**本文件所在仓库**上：脚本从哪个 cwd 跑都行，且产物逐字节一致。
// 上一版写的是 cwd 相对路径（'src/update/host/index.ts' / 'lib/update.js'），在仓根外裸跑直接 exit 1
// （复审 V6② 实测：在 C:\ 下跑同一条命令挂掉）—— 构建脚本不该要求「先 cd 到仓根」。
// absWorkingDir 也要给：esbuild 的源码注释路径是按工作目录算的，工作目录一变，产物里那几行
// `// src/update/host/index.ts` 就会变成绝对路径 —— 那样同一份源码在两个 cwd 下会产出不同字节。
const ROOT = fileURLToPath(new URL('../../', import.meta.url))
const entry = fileURLToPath(new URL('../../src/update/host/index.ts', import.meta.url))
const outfile = fileURLToPath(new URL('../../lib/update.js', import.meta.url))

const result = await build({
  absWorkingDir: ROOT,
  entryPoints: [entry],
  outfile,
  bundle: true,
  format: 'esm',
  platform: 'node',
  target: 'node22',
  sourcemap: false,
  logLevel: 'info',
  legalComments: 'none',
  external: ['dsh-plugin-update'],
  banner: {
    js: '// AUTO-GENERATED by node scripts/update/build-host.mjs — DO NOT EDIT. Source: src/update/host/index.ts',
  },
})

if (result.errors.length > 0) {
  console.error('build-host: 打包失败')
  process.exit(1)
}
