/**
 * 宿主半打包（#39）：src/update/host/index.ts → lib/update.js
 *
 * 为什么要有这一步：客户端半走 tsdown（`lib/client.js`），宿主半却是检入的 JS；更新能力要在
 * 宿主里 import 第三方包 `dsh-plugin-update`，还带一层 `../bridge.js` 的类型，所以给它一条
 * 最小构建步骤（只用 esbuild，不引第二套打包器）。源码住 `src/update/host/`，`lib/` 只放产物；
 * 产物与 `lib/index.js` / `lib/log/index.js` 一样入库（用户从 npm 装到的就是这个 lib/）。
 *
 * `dsh-plugin-update` **内联进产物**（#58 拍板，上一版是 externals，已推翻）：
 *
 * 更新包的 `dist/reader.js:102` 与 `dist/host.js:83` 用
 * `containingPackage(fileURLToPath(import.meta.url), 'dsh-prompt')` 反推「正在运行的包」，
 * 并从这里取 `runningVersion`（取不到就在 `dist/host.js:85` 抛 `unknown-profile`，三条路由全降级）。
 * `import.meta.url` 属于**这段代码实际住的那个文件**：留 externals 时它住在
 * `<profile>/node_modules/dsh-plugin-update/dist/{reader,host}.js`，而真机 profile 是 DSH 自己写死的
 * **hoisted** 布局（app.asar：`nodeLinker: hoisted`，不一致还会改回来）⇒ 上溯到盘根都没有一个叫
 * `dsh-prompt` 的 package.json ⇒ `loaded = null` ⇒ 部署到真机后三条更新路由只会回 `unknown-profile`
 * （受控复现见 `scripts/test-issue-39.cjs` 的 13) 段与 `.wayfinder/update/58-progress.md`）。
 * 内联后这段代码住在 `lib/update.js`，即**本插件包内** ⇒ 上溯第一个命中的就是本插件包的
 * `package.json`（`name = "dsh-prompt"`）⇒ `loaded == installed`。
 *
 * 代价（明写在这里，别当成没发生）：更新包的版本被**冻结在构建期** —— 升它要改 devDependencies
 * 再重建、重新发版（`lib/update.js` 本来就是入库的构建产物，升级路径与别处一致）；
 * `package.json` 里它从 `dependencies` 降到 `devDependencies`，用户装到的包里不再另装它
 * —— 这正是要的效果（本插件自包含，不依赖「插件包外恰好有一份更新包」）。
 * 回归：`scripts/test-issue-39.cjs` 的 1) 段钉住产物里没有裸 import，13) 段钉住
 * 「插件包外那层 node_modules 里有没有更新包都不影响」。
 */
import { build } from 'esbuild'
import { fileURLToPath } from 'node:url'

// 入口 / 产物 / 工作目录都钉在**本文件所在仓库**上：脚本从哪个 cwd 跑都行，且产物逐字节一致。
// 上一版写的是 cwd 相对路径（'src/update/host/index.ts' / 'lib/update.js'），在仓根外裸跑直接 exit 1
// （复审 V6② 实测：在 C:\ 下跑同一条命令挂掉）—— 构建脚本不该要求「先 cd 到仓根」。
// absWorkingDir 也要给：esbuild 的源码注释路径是按工作目录算的，工作目录一变，产物里那几行
// `// src/update/host/index.ts` 就会变成绝对路径 —— 那样同一份源码在两个 cwd 下会产出不同字节。
const ROOT = fileURLToPath(new URL('../../', import.meta.url))
const entry = fileURLToPath(new URL('../../src/update/host/index.ts', import.meta.url))
const outfile = fileURLToPath(new URL('../../lib/update.js', import.meta.url))

const result = await build({
  absWorkingDir: ROOT,
  entryPoints: [entry],
  outfile,
  bundle: true,
  format: 'esm',
  platform: 'node',
  target: 'node22',
  sourcemap: false,
  logLevel: 'info',
  legalComments: 'none',
  banner: {
    js: '// AUTO-GENERATED by node scripts/update/build-host.mjs — DO NOT EDIT. Source: src/update/host/index.ts',
  },
})

if (result.errors.length > 0) {
  console.error('build-host: 打包失败')
  process.exit(1)
}
