/**
 * 宿主半打包（#39）：src/update/host/index.ts → lib/update.js
 *
 * 为什么要有这一步：客户端半走 tsdown（`lib/client.js`），宿主半却是检入的 JS；更新能力要在
 * 宿主里 import 第三方包 `dsh-plugin-update`，还带一层 `../bridge.js` 的类型，所以给它一条
 * 最小构建步骤（只用 esbuild，不引第二套打包器）。源码住 `src/update/host/`，`lib/` 只放产物；
 * 产物与 `lib/index.js` / `lib/log/index.js` 一样入库（用户从 npm 装到的就是这个 lib/）。
 *
 * `dsh-plugin-update` 保持外部（externals）：运行时按包名 import，走 profile 的 node_modules，
 * 升级只改 package.json 一处版本号；打死进产物会让两处版本各自漂移（wf 就吃了这个亏）。
 */
import { build } from 'esbuild'

const result = await build({
  entryPoints: ['src/update/host/index.ts'],
  outfile: 'lib/update.js',
  bundle: true,
  format: 'esm',
  platform: 'node',
  target: 'node22',
  sourcemap: false,
  logLevel: 'info',
  legalComments: 'none',
  external: ['dsh-plugin-update'],
  banner: {
    js: '// AUTO-GENERATED by node scripts/update/build-host.mjs — DO NOT EDIT. Source: src/update/host/index.ts',
  },
})

if (result.errors.length > 0) {
  console.error('build-host: 打包失败')
  process.exit(1)
}
